//! Soli WASM Worker — Cloudflare Workers fetch handler.
//! This file is the entry point for a Soli web application compiled to WASM.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use worker::*;

/// Embedded Soli source files — generated by `soli build --target wasm`.
pub mod bundle;

/// A request hash extracted from the Workers `Request`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SoliRequest {
    pub method: String,
    pub path: String,
    pub query: HashMap<String, String>,
    pub headers: HashMap<String, String>,
    pub body: Option<String>,
}

/// Cloudflare Workers fetch event handler.
#[event(fetch)]
pub async fn main(req: Request, _env: Env, _ctx: Context) -> Result<Response> {
    let method = req.method().to_string();
    let path = req.path();
    let query = req.query::<HashMap<String, String>>().unwrap_or_default();
    let body = req.text().await.ok();

    let mut headers = HashMap::new();
    if let Ok(entries) = req.headers().entries() {
        for entry in entries.flatten() {
            headers.insert(entry.0, entry.1);
        }
    }

    let soli_req = SoliRequest {
        method,
        path,
        query,
        headers,
        body,
    };

    match handle_request(&soli_req) {
        Ok(resp) => Ok(resp),
        Err(e) => {
            let error = serde_json::json!({
                "error": "Soli execution failed",
                "message": format!("{}", e)
            });
            Response::error(format!("{}", e), 500)
        }
    }
}

/// Handle a request by running the Soli application.
fn handle_request(req: &SoliRequest) -> Result<Response> {
    let sources = bundle::get_sources();

    // Try to find the main entry point
    let entry = sources
        .iter()
        .find(|(path, _)| {
            *path == &"app/controllers/application_controller.sl"
                || *path == &"app.sl"
                || *path == &"main.sl"
        })
        .or_else(|| sources.iter().next());

    let Some((_entry_path, entry_source)) = entry else {
        return Response::error("No Soli source files found in bundle", 500);
    };

    // Execute the Soli source through the interpreter
    match solilang::run(entry_source) {
        Ok(()) => Response::ok("Hello from Soli WASM Worker!"),
        Err(e) => Response::error(format!("Soli error: {}", e), 500),
    }
}
