# Registered relying party — generated by `soli generate oidc_provider`.
# Collection: oauth_clients
#
# Register one from a console or a seed:
#
#   result = OauthClient.register("My App", ["https://app.example/callback"],
#                                 { "client_type": "confidential" })
#   print(result["client_id"])
#   print(result["client_secret"])   # shown once — only its digest is stored

class OauthClient < Model
  # Fields: client_id, client_secret_digest, client_type, name, redirect_uris,
  # scopes, grant_types, require_pkce, skip_consent, disabled_at.

  # Create a client and return the credentials. The secret is returned in the
  # clear exactly once, because only its Argon2 digest is persisted.
  def self.register(name, redirect_uris, options)
    options = options ?? {}
    client_type = options["client_type"] ?? "confidential"
    invalid = redirect_uris.filter(fn(uri) !OauthClient.valid_redirect_uri?(uri))
    if invalid.length() != 0
      throw("redirect_uris must be absolute http(s) URLs without a fragment: #{invalid.join(", ")}")
    end

    attributes = {
      "client_id": nanoid(24),
      "name": name,
      "client_type": client_type,
      "redirect_uris": redirect_uris,
      "scopes": options["scopes"] ?? ["openid", "profile", "email", "offline_access"],
      "grant_types": options["grant_types"] ?? ["authorization_code", "refresh_token"],
      # A public client cannot keep a secret, so PKCE is the only thing binding
      # the code to the requester. Never let it be switched off for one.
      "require_pkce": client_type == "public" ? true : (options["require_pkce"] ?? true),
      "skip_consent": options["skip_consent"] ?? false,
      "client_secret_digest": null,
      "disabled_at": null
    }

    secret = ""
    if client_type == "confidential"
      secret = Crypto.random_token()
      attributes["client_secret_digest"] = Crypto.argon2_hash(secret)
    end

    client = OauthClient.create(attributes)

    return { "client": client, "client_id": attributes["client_id"], "client_secret": secret }
  end

  # `redirect_external` (and the spec) only accept absolute http(s) URLs, and
  # RFC 6749 §3.1.2 forbids a fragment. Rejecting at registration means the
  # failure surfaces here rather than mid-flow with a half-built authorization.
  def self.valid_redirect_uri?(uri)
    return false if uri.to_s.blank?
    return false if uri.to_s.contains("#")

    return uri.to_s.starts_with("http://") || uri.to_s.starts_with("https://")
  end

  def self.find_active(client_id)
    return null if client_id.to_s.blank?

    client = OauthClient.find_by("client_id", client_id.to_s)
    return null if client.nil?
    return null unless client["disabled_at"].nil?

    return client
  end

  def public?
    return this.client_type == "public"
  end

  # Exact match against a registered URI — byte for byte, no prefix matching,
  # no wildcards, no normalization. Anything looser lets an attacker who can
  # register a lookalike path harvest authorization codes.
  def redirect_uri_allowed?(candidate)
    return false if candidate.to_s.blank?

    return (this.redirect_uris ?? []).includes?(candidate.to_s)
  end

  def authenticate_secret(secret)
    return false if this.client_secret_digest.blank?
    return false if secret.to_s.blank?

    return Crypto.argon2_verify(secret.to_s, this.client_secret_digest)
  end

  # Narrow a requested scope set to what this client may actually have. An
  # unknown scope is dropped rather than rejected, per RFC 6749 §3.3.
  def allowed_scopes(requested)
    granted = this.scopes ?? []

    return requested.filter(fn(scope) granted.includes?(scope) && OIDC_SUPPORTED_SCOPES.includes?(scope))
  end

  def supports_grant?(grant_type)
    return (this.grant_types ?? []).includes?(grant_type.to_s)
  end
end
