# Device authorization grant (RFC 8628) — generated by `soli generate oidc_provider`.
# Collection: oauth_device_codes
#
# For input-constrained clients (a TV, a CLI): the device gets a `device_code`
# it polls with and a short `user_code` the person types on their phone or
# laptop. Only the digest of the device code is stored.

class OauthDeviceCode < Model
  # Fields: device_code_digest, user_code, client_id, scope, status
  # ("pending" | "approved" | "denied"), user_key, auth_time, interval,
  # last_polled_at, expires_at, consumed_at, refresh_chain_id.

  # Returns {device_code, user_code, expires_in, interval}. The device code is
  # shown to the device once; only its digest is persisted.
  static def issue(client_id, scopes)
    device_code = Crypto.random_token()
    user_code = OauthDeviceCode.generate_user_code()
    now = DateTime.utc().to_unix()

    OauthDeviceCode.create({
      "device_code_digest": Crypto.sha256(device_code),
      "user_code": OauthDeviceCode.normalize(user_code),
      "client_id": client_id,
      "scope": scopes.join(" "),
      "status": "pending",
      "user_key": nil,
      "auth_time": nil,
      "interval": OIDC_DEVICE_INTERVAL,
      "last_polled_at": 0,
      "expires_at": now + OIDC_DEVICE_CODE_TTL,
      "consumed_at": nil,
      "refresh_chain_id": uuid_v4()
    })

    return {
      "device_code": device_code,
      "user_code": user_code,
      "expires_in": OIDC_DEVICE_CODE_TTL,
      "interval": OIDC_DEVICE_INTERVAL
    }
  end

  # `WDJB-MJHT`: eight letters from 20 (2.5e10 combinations), drawn from bytes
  # below 240 so that `byte % 20` is not biased towards the first letters.
  #
  # The alphabet has no vowels and no look-alikes (0/O, 1/I): a code read aloud
  # or squinted at on a TV should survive.
  static def generate_user_code
    alphabet = "BCDFGHJKLMNPQRSTVWXZ"
    letters = []
    while letters.length() < 8
      Crypto.random_bytes(16).each do |byte|
        next if byte >= 240
        next if letters.length() >= 8

        letters.push(alphabet.substring(byte % 20, byte % 20 + 1))
      end
    end

    return letters.slice(0, 4).join("") + "-" + letters.slice(4, 8).join("")
  end

  # What the person typed, made comparable: case and separators do not matter.
  static def normalize(user_code)
    return user_code.to_s.upcase().replace("-", "").replace(" ", "").trim()
  end

  static def find_by_user_code(user_code)
    normalized = OauthDeviceCode.normalize(user_code)
    return nil if normalized.blank?

    row = OauthDeviceCode.find_by("user_code", normalized)
    return nil if row.nil?
    return nil if row["expires_at"] <= DateTime.utc().to_unix()

    return row
  end

  static def find_by_device_code(device_code)
    return nil if device_code.to_s.blank?

    return OauthDeviceCode.find_by("device_code_digest", Crypto.sha256(device_code.to_s))
  end

  # Record the person's decision. Only a still-pending code can be decided, so
  # a second tab cannot flip an answer already given.
  static def decide(user_code, approved, user_key, auth_time)
    normalized = OauthDeviceCode.normalize(user_code)
    now = DateTime.utc().to_unix()
    status = approved ? "approved" : "denied"
    rows = @sdbql{
      FOR d IN oauth_device_codes
        FILTER d.user_code == #{normalized} AND d.status == "pending" AND d.expires_at > #{now}
        UPDATE d WITH { status: #{status}, user_key: #{user_key}, auth_time: #{auth_time} } IN oauth_device_codes
        RETURN NEW
    }
    return nil unless rows.is_a?("array")

    return rows.first()
  end

  # Called on every poll. Returns {"error": <rfc8628 code>} while the device
  # must keep waiting, or {"row": <approved row>} exactly once — the row is
  # consumed in the same statement that reads it, so two racing polls cannot
  # both walk away with tokens.
  static def poll(device_code, client_id)
    row = OauthDeviceCode.find_by_device_code(device_code)
    return {"error": "invalid_grant"} if row.nil?
    return {"error": "invalid_grant"} if row["client_id"] != client_id
    return {"error": "invalid_grant"} unless row["consumed_at"].nil?

    now = DateTime.utc().to_unix()
    return {"error": "expired_token"} if row["expires_at"] <= now

    # Polling faster than `interval` gets slow_down and a longer interval
    # (RFC 8628 §3.5): a client that ignores it cannot hammer the endpoint.
    if now - row["last_polled_at"] < row["interval"]
      row.interval = row["interval"] + 5
      row.last_polled_at = now
      row.update()

      return {"error": "slow_down"}
    end
    row.last_polled_at = now
    row.update()

    return {"error": "authorization_pending"} if row["status"] == "pending"
    return {"error": "access_denied"} if row["status"] == "denied"

    digest = row["device_code_digest"]
    rows = @sdbql{
      FOR d IN oauth_device_codes
        FILTER d.device_code_digest == #{digest} AND d.status == "approved" AND d.consumed_at == null
        UPDATE d WITH { consumed_at: #{now} } IN oauth_device_codes
        RETURN NEW
    }
    return {"error": "invalid_grant"} unless rows.is_a?("array") && rows.length() == 1

    return {"row": rows.first()}
  end
end
