# Authorization code — generated by `soli generate oidc_provider`.
# Collection: oauth_authorization_codes
#
# Codes are single-use, short-lived, and bound to the client, the redirect_uri
# and the PKCE challenge they were issued against. Only the SHA-256 digest is
# stored, so a database leak cannot be replayed against the token endpoint.

class OauthAuthorizationCode < Model
  # Fields: code_digest, client_id, user_key, redirect_uri, scope, nonce,
  # code_challenge, code_challenge_method, auth_time, expires_at, used_at,
  # refresh_chain_id.

  # Issue a code and return the plaintext (which goes in the redirect).
  def self.issue(attributes)
    code = Crypto.random_token()
    now = DateTime.utc().to_unix()

    OauthAuthorizationCode.create({
      "code_digest": Crypto.sha256(code),
      "client_id": attributes["client_id"],
      "user_key": attributes["user_key"],
      "redirect_uri": attributes["redirect_uri"],
      "scope": attributes["scope"],
      "nonce": attributes["nonce"],
      "code_challenge": attributes["code_challenge"],
      "code_challenge_method": attributes["code_challenge_method"],
      "auth_time": attributes["auth_time"],
      "expires_at": now + OIDC_CODE_TTL,
      "used_at": null,
      # Minted here rather than at first exchange: if this code is later
      # replayed, we need to know which token family the *first* exchange
      # created in order to revoke it.
      "refresh_chain_id": uuid_v4()
    })

    return code
  end

  # Atomically consume a code, returning the row — or nil if it was already
  # used, expired or never existed.
  #
  # The filter and the update are one statement so two simultaneous exchanges
  # cannot both win: the second re-evaluates the filter, finds `used_at` set,
  # and matches zero documents. A read-then-write would race, and that race is
  # worth a stolen authorization code.
  #
  # `RETURN NEW` rather than `RETURN OLD` because SolidB does not support the
  # latter. It makes no difference here: the update only touches `used_at`, and
  # every field the caller needs is carried unchanged.
  def self.burn(code)
    return null if code.to_s.blank?

    digest = Crypto.sha256(code.to_s)
    now = DateTime.utc().to_unix()
    rows = @sdbql{
      FOR c IN oauth_authorization_codes
        FILTER c.code_digest == #{digest} AND c.used_at == null AND c.expires_at > #{now}
        UPDATE c WITH { used_at: #{now} } IN oauth_authorization_codes
        RETURN NEW
    }
    # A failed query comes back as an error *string*, not a raised error, so a
    # non-array result must be treated as "did not burn" rather than trusted.
    return null unless rows.is_a?("array")

    return rows.first()
  end

  # A code presented after it was already burned. That is either a replay
  # attack or a leaked code, and RFC 6749 §4.1.2 says to revoke everything the
  # original exchange produced.
  def self.find_used(code)
    return null if code.to_s.blank?

    row = OauthAuthorizationCode.find_by("code_digest", Crypto.sha256(code.to_s))
    return null if row.nil?
    return null if row["used_at"].nil?

    return row
  end

  # PKCE (RFC 7636 §4.6). Only S256 is accepted — `plain` is deprecated by
  # OAuth 2.1 and accepting it only adds a downgrade path.
  def self.verify_pkce(challenge, method, verifier)
    return false unless method.to_s == "S256"
    return false if challenge.to_s.blank?
    return false if verifier.to_s.blank?

    computed = Base64.urlsafe_encode(Hex.decode(Crypto.sha256(verifier.to_s)))

    return Crypto.secure_compare(computed, challenge.to_s)
  end
end
