# Refresh token — generated by `soli generate oidc_provider`.
# Collection: oauth_refresh_tokens
#
# Refresh tokens rotate: every use issues a new one and retires the old. A
# retired token being presented again means it leaked, so the whole family
# (`chain_id`) is revoked — the legitimate holder and the attacker both lose
# access, which is the correct outcome because we cannot tell them apart.

class OauthRefreshToken < Model
  # Fields: token_digest, chain_id, client_id, user_key, scope, issued_at,
  # expires_at, rotated_at, revoked_at, revoked_reason, access_jti.

  def self.issue(chain_id, client_id, user_key, scopes, access_jti)
    token = Crypto.random_token()
    now = DateTime.utc().to_unix()

    OauthRefreshToken.create({
      "token_digest": Crypto.sha256(token),
      "chain_id": chain_id,
      "client_id": client_id,
      "user_key": user_key,
      "scope": scopes.join(" "),
      "issued_at": now,
      "expires_at": now + OIDC_REFRESH_TOKEN_TTL,
      "rotated_at": null,
      "revoked_at": null,
      "revoked_reason": null,
      "access_jti": access_jti
    })

    return token
  end

  def self.find_by_token(token)
    return null if token.to_s.blank?

    return OauthRefreshToken.find_by("token_digest", Crypto.sha256(token.to_s))
  end

  # Revoke every token in a family and denylist the access tokens they were
  # issued alongside, so a detected leak does not leave a live credential.
  def self.revoke_chain(chain_id, reason)
    return 0 if chain_id.to_s.blank?

    now = DateTime.utc().to_unix()
    tokens = OauthRefreshToken.where({ "chain_id": chain_id.to_s })
    tokens.each do |token|
      OauthRevocation.revoke(token["access_jti"], reason)
      next unless token["revoked_at"].nil?

      token.revoked_at = now
      token.revoked_reason = reason
      token.update()
    end

    return tokens.length()
  end

  def active?
    return false unless this.revoked_at.nil?
    return false unless this.rotated_at.nil?
    return false if this.expires_at.nil?

    return DateTime.utc().to_unix() < this.expires_at
  end

  # Already rotated = this token was superseded by a newer one. Seeing it again
  # is the reuse signal.
  def reused?
    return !this.rotated_at.nil?
  end

  def mark_rotated
    this.rotated_at = DateTime.utc().to_unix()

    return this.update()
  end

  def scopes
    return oidc_scope_list(this.scope)
  end
end
