# UserInfo endpoint — generated by `soli generate oidc_provider`.
#
# The one place a relying party can ask "who is this token for?". Claims are
# gated by the scopes the user actually consented to, so an `openid`-only token
# gets a subject identifier and nothing else.

class OauthUserinfoController < Controller
  # GET|POST /oauth/userinfo
  def show
    token = oidc_bearer_token(req)
    claims = oidc_verify_access_token(token)
    if claims.nil?
      return this._unauthorized("The access token is invalid, expired or revoked")
    end

    user = User.find_by("_key", claims["sub"].to_s)
    if user.nil?
      return this._unauthorized("The user no longer exists")
    end

    scopes = oidc_scope_list(claims["scope"])
    body = oidc_user_claims(user, scopes)
    body["sub"] = user["_key"]

    return oidc_json(body, 200)
  end

  # RFC 6750 §3: a bad bearer token is answered with a challenge, so the client
  # knows to refresh rather than guessing at the failure.
  def _unauthorized(description)
    return {
      "status": 401,
      "headers": {
        "Content-Type": "application/json;charset=UTF-8",
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
        "WWW-Authenticate": "Bearer error=\"invalid_token\", error_description=\"#{description}\""
      },
      "body": { "error": "invalid_token", "error_description": description }.to_json()
    }
  end
end
