# Recorded consent — generated by `soli generate oidc_provider`.
# Collection: oauth_consents
#
# One row per (user, client). Remembering the grant is what stops the consent
# screen appearing on every single sign-in.

class OauthConsent < Model
  # Fields: user_key, client_id, scopes, granted_at, revoked_at.

  def self.for_pair(user_key, client_id)
    return null if user_key.to_s.blank? || client_id.to_s.blank?

    rows = OauthConsent.where({ "user_key": user_key.to_s, "client_id": client_id.to_s })

    return rows.first()
  end

  # True when this user has already granted *every* scope now being asked for.
  # A request that widens the scope must be consented to again.
  def self.covers?(user_key, client_id, scopes)
    consent = OauthConsent.for_pair(user_key, client_id)
    return false if consent.nil?
    return false unless consent["revoked_at"].nil?

    granted = consent["scopes"] ?? []

    return scopes.filter(fn(scope) !granted.includes?(scope)).length() == 0
  end

  # Record a grant, merging with anything previously granted.
  def self.grant(user_key, client_id, scopes)
    consent = OauthConsent.for_pair(user_key, client_id)
    now = DateTime.utc().to_unix()

    if consent.nil?
      return OauthConsent.create({
        "user_key": user_key.to_s,
        "client_id": client_id.to_s,
        "scopes": scopes,
        "granted_at": now,
        "revoked_at": null
      })
    end

    merged = consent["scopes"] ?? []
    scopes.each do |scope|
      merged.push(scope) unless merged.includes?(scope)
    end
    consent.scopes = merged
    consent.granted_at = now
    consent.revoked_at = null

    return consent.update()
  end

  # Withdraw consent and kill the live tokens. Without the second half the user
  # would keep seeing an app they just disconnected.
  def self.revoke(user_key, client_id)
    consent = OauthConsent.for_pair(user_key, client_id)
    return false if consent.nil?

    consent.revoked_at = DateTime.utc().to_unix()
    consent.update()
    OauthRefreshToken.where({ "user_key": user_key.to_s, "client_id": client_id.to_s })
      .each do |token|
        OauthRefreshToken.revoke_chain(token["chain_id"], "consent_revoked")
      end

    return true
  end
end
