# Authorization endpoint — generated by `soli generate oidc_provider`.
#
# The order of validation here is load-bearing, not stylistic. `client_id` and
# `redirect_uri` are checked *first* and their failures render a page instead
# of redirecting: bouncing the browser to an unverified `redirect_uri` is
# exactly the open redirect RFC 6749 §4.1.2.1 carves those two errors out to
# prevent. Only once the URI is known-registered may an error be handed back
# to the client.

class OauthAuthorizationsController < Controller
  static {
    this.layout = "application"
  }

  # GET /oauth/authorize
  def new
    context = this._validate_request()
    return context["response"] unless context["response"].nil?

    client = context["client"]
    scopes = context["scopes"]

    user = current_user()
    if user.nil?
      # Come back here once they have signed in. The full query string is kept
      # so no authorization parameter is lost across the round trip.
      session_set("oidc_return_to", "/oauth/authorize?#{req["query_string"].to_s}")

      return redirect("/login")
    end

    if client.skip_consent == true || OauthConsent.covers?(user["_key"], client.client_id, scopes)
      return this._issue_code(context, user, scopes)
    end

    return render(
      "oauth_authorizations/new",
      {
        "title": "Authorize #{client.name}",
        "client": client,
        "scopes": scopes.map(fn(scope) { {
          "name": scope,
          "description": scope_description(scope)
        } }),
        "params": context["params"]
      }
    )
  end

  # POST /oauth/authorize — the consent decision.
  #
  # Everything is re-validated against the database rather than trusted from
  # the hidden fields, which the user controls.
  def create
    context = this._validate_request()
    return context["response"] unless context["response"].nil?

    user = current_user()
    return redirect("/login") if user.nil?

    client = context["client"]
    scopes = context["scopes"]

    if params["approve"].to_s != "1"
      return oidc_authorize_error(
        context["redirect_uri"],
        "access_denied",
        "The user declined the request",
        context["state"]
      )
    end

    OauthConsent.grant(user["_key"], client.client_id, scopes)

    this._issue_code(context, user, scopes)
  end

  # --- internals -------------------------------------------------------------

  # Validate the request parameters common to both actions. Returns a context
  # hash; a non-nil "response" key means validation failed and that response
  # should be returned as-is.
  def _validate_request
    client_id = params["client_id"].to_s

    client = OauthClient.find_active(client_id)
    return {"response": oidc_authorize_fatal("Unknown or disabled client application.")} if client.nil?

    # A signed request object (RFC 9101) replaces the query parameters wholesale:
    # the point is that nothing outside the signature can steer the request.
    effective = params
    if params["request"].to_s.present?
      request_object = this._request_object(client)
      return {"response": request_object["response"]} unless request_object["response"].nil?

      effective = request_object["claims"]
    end
    redirect_uri = effective["redirect_uri"].to_s
    state = effective["state"].to_s

    if !(client.redirect_uri_allowed?(redirect_uri))
      return {"response": oidc_authorize_fatal("The redirect_uri is not registered for this client application.")}
    end

    # Past this point the redirect_uri is trusted, so errors may go back to it.
    invalid = this._parameter_error(client, effective)
    if !invalid.nil?
      return {"response": oidc_authorize_error(redirect_uri, invalid["code"], invalid["description"], state)}
    end

    scopes = client.allowed_scopes(oidc_scope_list(effective["scope"]))
    if !(scopes.includes?("openid"))
      return {"response": oidc_authorize_error(redirect_uri, "invalid_scope", "The openid scope is required", state)}
    end

    return {
      "response": null,
      "client": client,
      "scopes": scopes,
      "redirect_uri": redirect_uri,
      "state": state,
      "params": {
        "client_id": client_id,
        "redirect_uri": redirect_uri,
        "state": state,
        "scope": scopes.join(" "),
        "nonce": effective["nonce"].to_s,
        "code_challenge": effective["code_challenge"].to_s,
        "code_challenge_method": effective["code_challenge_method"].to_s
      }
    }
  end

  # Returns nil when the request is well-formed, or {code, description}.
  def _parameter_error(client, effective)
    if effective["response_type"].to_s != "code"
      return {"code": "unsupported_response_type", "description": "Only the authorization code flow is supported"}
    end

    if !(client.supports_grant?("authorization_code"))
      return {"code": "unauthorized_client", "description": "This client may not use the authorization code grant"}
    end

    this._pkce_error(client, effective)
  end

  def _pkce_error(client, effective)
    challenge = effective["code_challenge"].to_s
    method = effective["code_challenge_method"].to_s

    if challenge.blank?
      return null unless client.require_pkce == true
      return {"code": "invalid_request", "description": "code_challenge is required"}
    end

    # `plain` offers no protection against an attacker who intercepted the
    # authorization request, and OAuth 2.1 drops it. Rejecting it outright
    # keeps a downgrade off the table.
    if method != "S256"
      return {"code": "invalid_request", "description": "code_challenge_method must be S256"}
    end

    null
  end

  # Verify `request=<jwt>` against the key registered for this client
  # (`request_object_key`, a public PEM; RS256 only). The object must be issued
  # by the client for this provider. `request_uri` is not supported: fetching a
  # URL supplied by the caller is an SSRF door we would rather keep shut.
  # Every failure is a page, not a redirect — the redirect_uri inside an
  # unverified object is the one thing that must not be trusted.
  def _request_object(client)
    key = client.request_object_key.to_s
    if key.blank?
      return {"response": oidc_authorize_fatal("This client has no registered request-object key.")}
    end

    claims = jwt_verify(params["request"].to_s, "", {
      "algorithm": "RS256",
      "key": key,
      "issuer": client.client_id,
      "audience": oidc_issuer()
    }) rescue nil
    if claims.nil? || claims["error"] == true
      return {"response": oidc_authorize_fatal("The request object is invalid or its signature does not verify.")}
    end

    # RFC 9101 §6.3: client_id inside the object must agree with the outside.
    if claims["client_id"].to_s != client.client_id
      return {"response": oidc_authorize_fatal("The request object was issued for a different client.")}
    end

    {"response": nil, "claims": claims}
  end

  def _issue_code(context, user, scopes)
    stored = context["params"]
    code = OauthAuthorizationCode.issue({
      "client_id": context["client"].client_id,
      "user_key": user["_key"],
      "redirect_uri": context["redirect_uri"],
      "scope": scopes.join(" "),
      "nonce": stored["nonce"],
      "code_challenge": stored["code_challenge"],
      "code_challenge_method": stored["code_challenge_method"],
      "auth_time": session_get("auth_time") ?? DateTime.utc().to_unix()
    })

    separator = oidc_query_separator(context["redirect_uri"])
    location = "#{context["redirect_uri"]}#{separator}code=#{url_encode(code)}"
    # `state` is opaque to us and echoed verbatim — it is the client's CSRF
    # defense, and rewriting it in any way would break that.
    location = "#{location}&state=#{url_encode(context["state"])}" unless context["state"].blank?

    redirect_external(location)
  end
end
