# Dynamic client registration (RFC 7591) — generated by `soli generate oidc_provider`.
#
# Off unless SOLI_OIDC_REGISTRATION_TOKEN is set. That value is the *initial
# access token* (RFC 7591 §3): whoever holds it may register clients, so hand
# it to the people or systems that should be able to, not to the public. An
# open registration endpoint lets anyone mint a client that then appears on your
# consent screen under a name of their choosing.
#
# What a registering caller can NOT do, whatever the metadata says:
#   * ask for `client_credentials` (machine access is granted by an admin),
#   * set `skip_consent`,
#   * request scopes outside OIDC_SUPPORTED_SCOPES.

class OauthRegistrationsController < Controller
  # POST /oauth/register
  def create
    expected = oidc_registration_token()
    # Disabled means absent, not "forbidden": the endpoint should not advertise
    # itself to anyone who has not been given the token.
    return {"status": 404, "body": ""} if expected.blank?

    presented = oidc_bearer_token(req)
    if presented.blank? || !(Crypto.secure_compare(presented, expected))
      return this._invalid_token()
    end

    metadata = req["json"]
    return this._error("invalid_client_metadata", "Send a JSON object") unless type(metadata) == "hash"

    redirect_uris = metadata["redirect_uris"]
    if type(redirect_uris) != "array" || redirect_uris.length() == 0
      return this._error("invalid_redirect_uri", "redirect_uris must be a non-empty array")
    end
    bad = redirect_uris.filter(fn(uri) { !OauthClient.valid_redirect_uri?(uri) })
    if bad.length() != 0
      return this._error("invalid_redirect_uri", "Not an absolute http(s) URL without a fragment: #{bad.join(", ")}")
    end

    grant_types = metadata["grant_types"] ?? ["authorization_code"]
    unsupported = grant_types.filter(fn(grant) { !["authorization_code", "refresh_token"].includes?(grant) })
    if unsupported.length() != 0
      return this._error("invalid_client_metadata", "Unsupported grant_types: #{unsupported.join(", ")}")
    end

    auth_method = metadata["token_endpoint_auth_method"] ?? "client_secret_basic"
    unless ["client_secret_basic", "client_secret_post", "none"].includes?(auth_method)
      return this._error("invalid_client_metadata", "Unsupported token_endpoint_auth_method: #{auth_method}")
    end

    scopes = oidc_scope_list(metadata["scope"] ?? "openid")
    unknown = scopes.filter(fn(scope) { !OIDC_SUPPORTED_SCOPES.includes?(scope) })
    if unknown.length() != 0
      return this._error("invalid_client_metadata", "Unsupported scope: #{unknown.join(", ")}")
    end

    name = metadata["client_name"].to_s
    name = "Unnamed client" if name.blank?
    public_client = auth_method == "none"

    result = OauthClient.register(name, redirect_uris, {
      "client_type": public_client ? "public" : "confidential",
      "scopes": scopes,
      "grant_types": grant_types
    })

    body = {
      "client_id": result["client_id"],
      "client_id_issued_at": DateTime.utc().to_unix(),
      "client_name": name,
      "redirect_uris": redirect_uris,
      "grant_types": grant_types,
      "response_types": ["code"],
      "token_endpoint_auth_method": auth_method,
      "scope": scopes.join(" ")
    }
    unless public_client
      body["client_secret"] = result["client_secret"]
      body["client_secret_expires_at"] = 0
    end

    oidc_json(body, 201)
  end

  def _error(code, description)
    oidc_json({"error": code, "error_description": description}, 400)
  end

  def _invalid_token
    return {
      "status": 401,
      "headers": {
        "Content-Type": "application/json;charset=UTF-8",
        "Cache-Control": "no-store",
        "WWW-Authenticate": "Bearer error=\"invalid_token\""
      },
      "body": {"error": "invalid_token"}.to_json()
    }
  end
end
