# Device verification page — generated by `soli generate oidc_provider`.
#
# The person's half of RFC 8628: they open /oauth/device on a phone or laptop,
# type the code shown on the device, sign in if needed, and approve or deny.
# This is a real browser form, so unlike the token endpoints it keeps CSRF
# protection.

class OauthDeviceController < Controller
  static {
    this.layout = "application"
  }

  # GET /oauth/device[?user_code=WDJB-MJHT]
  def new
    user = current_user()
    if user.nil?
      session_set("oidc_return_to", req["query_string"].to_s.blank? ? "/oauth/device" : "/oauth/device?#{req["query_string"]}")

      return redirect("/login")
    end

    code = params["user_code"].to_s
    return render("oauth_device/new", {"title": "Connect a device", "step": "enter", "error": nil}) if code.blank?

    this._confirm_step(code)
  end

  # POST /oauth/device — either "look this code up" or the decision on it.
  def create
    user = current_user()
    return redirect("/login") if user.nil?

    code = params["user_code"].to_s
    return this._confirm_step(code) if params["approve"].to_s.blank?

    row = OauthDeviceCode.decide(code, params["approve"].to_s == "1", user["_key"], session_get("auth_time") ?? DateTime.utc().to_unix())
    return this._enter_step("That code is invalid, expired or already used.") if row.nil?

    if params["approve"].to_s == "1"
      client = OauthClient.find_active(row["client_id"])
      OauthConsent.grant(user["_key"], row["client_id"], oidc_scope_list(row["scope"])) unless client.nil?
    end

    render("oauth_device/new", {"title": "Connect a device", "step": params["approve"].to_s == "1" ? "approved" : "denied", "error": nil})
  end

  def _confirm_step(code)
    row = OauthDeviceCode.find_by_user_code(code)
    return this._enter_step("That code is invalid or has expired.") if row.nil? || row["status"] != "pending"

    client = OauthClient.find_active(row["client_id"])
    return this._enter_step("That code is invalid or has expired.") if client.nil?

    scopes = oidc_scope_list(row["scope"])
    render("oauth_device/new", {
      "title": "Connect a device",
      "step": "confirm",
      "error": nil,
      "user_code": OauthDeviceCode.normalize(code),
      "client": client,
      "scopes": scopes.map(fn(scope) { {"name": scope, "description": scope_description(scope)} })
    })
  end

  def _enter_step(message)
    render("oauth_device/new", {"title": "Connect a device", "step": "enter", "error": message})
  end
end
