# Access-token denylist — generated by `soli generate oidc_provider`.
# Collection: oauth_revocations
#
# Access tokens are self-contained JWTs, so a resource server verifying one
# offline cannot know it was revoked. This table closes that window for *this*
# provider's own endpoints (userinfo, refresh). It stays small because rows are
# only written on an explicit revoke or a detected token reuse, and each one
# can be dropped once `expires_at` has passed.

class OauthRevocation < Model
  # Fields: jti, expires_at, reason.

  def self.revoke(jti, reason)
    return false if jti.to_s.blank?
    return true if OauthRevocation.revoked?(jti)

    OauthRevocation.create({
      "jti": jti.to_s,
      "reason": reason,
      # Past this point the token has expired on its own and the row is
      # redundant — prune on whatever schedule suits you.
      "expires_at": DateTime.utc().to_unix() + OIDC_ACCESS_TOKEN_TTL
    })

    return true
  end

  def self.revoked?(jti)
    return false if jti.to_s.blank?

    return !OauthRevocation.find_by("jti", jti.to_s).nil?
  end
end
