# RP-initiated logout — generated by `soli generate oidc_provider`.

class OauthSessionsController < Controller
  # GET /oauth/logout
  #
  # Ends the session here, then optionally returns the browser to the relying
  # party. The return URI is honoured only when it is one the client
  # registered — an unchecked post_logout_redirect_uri is an open redirect in
  # exactly the same way the authorization endpoint's would be.
  def end_session
    destination = this._post_logout_destination()
    session_destroy()

    return redirect_external(destination) unless destination.blank?

    return redirect("/")
  end

  def _post_logout_destination
    requested = params["post_logout_redirect_uri"].to_s
    return "" if requested.blank?

    hint = params["id_token_hint"].to_s
    return "" if hint.blank?

    # The hint is not a credential — it only tells us which client is asking,
    # so we can check the URI against that client's registrations. It is read
    # without verification and nothing is trusted from it beyond the audience.
    decoded = jwt_decode_unsafe(hint)
    return "" if decoded["error"] == true

    client = OauthClient.find_active(decoded["claims"]["aud"].to_s)
    return "" if client.nil?
    return "" unless client.redirect_uri_allowed?(requested)

    return requested
  end
end
