# Token endpoint — generated by `soli generate oidc_provider`.
#
# Called server-to-server by relying parties, so there is no browser session
# and no CSRF token; the *client* is authenticated instead, and public clients
# rely on PKCE. `skip_csrf("/oauth/token")` in config/routes.sl is what makes
# that possible — without it the same-origin gate rejects every legitimate call.
#
# Every response goes through `oidc_json`, which sets the `Cache-Control:
# no-store` RFC 6749 §5.1 requires: these bodies contain bearer credentials and
# must not sit in a proxy cache.

class OauthTokensController < Controller
  # POST /oauth/token
  def create
    grant_type = params["grant_type"].to_s

    auth = this._authenticate_client()
    return auth["response"] unless auth["response"].nil?

    return this._authorization_code_grant(auth["client"]) if grant_type == "authorization_code"
    return this._refresh_token_grant(auth["client"]) if grant_type == "refresh_token"

    return oidc_token_error("unsupported_grant_type", "Unsupported grant_type: #{grant_type}", 400)
  end

  # POST /oauth/revoke (RFC 7009)
  #
  # Always answers 200, even for an unknown token: telling a caller whether a
  # token existed is an oracle, and the RFC requires success either way.
  def revoke
    auth = this._authenticate_client()
    return auth["response"] unless auth["response"].nil?

    token = OauthRefreshToken.find_by_token(params["token"].to_s)
    if !token.nil? && token["client_id"] == auth["client"].client_id
      OauthRefreshToken.revoke_chain(token["chain_id"], "client_revoked")
    end

    return oidc_json({}, 200)
  end

  # --- grants ----------------------------------------------------------------

  def _authorization_code_grant(client)
    code = params["code"].to_s
    redirect_uri = params["redirect_uri"].to_s

    row = OauthAuthorizationCode.burn(code)
    if row.nil?
      return this._handle_replay(code)
    end

    mismatch = this._code_mismatch(row, client, redirect_uri)
    return mismatch unless mismatch.nil?

    scopes = oidc_scope_list(row["scope"])
    user = User.find_by("_key", row["user_key"])
    if user.nil?
      return oidc_token_error("invalid_grant", "The user no longer exists", 400)
    end

    return this._issue_tokens(client, user, scopes, row["refresh_chain_id"], row["nonce"],
                              row["auth_time"])
  end

  # A code that did not burn was either never valid, or already used. The
  # second case is a genuine replay: the code leaked, so everything the first
  # exchange produced has to go (RFC 6749 §4.1.2).
  def _handle_replay(code)
    used = OauthAuthorizationCode.find_used(code)
    if !used.nil?
      OauthRefreshToken.revoke_chain(used["refresh_chain_id"], "code_replayed")
    end

    return oidc_token_error("invalid_grant", "Authorization code is invalid, expired or used", 400)
  end

  # Every binding made at authorization time is re-checked here. A code is only
  # good for the client, redirect_uri and PKCE challenge it was issued against.
  def _code_mismatch(row, client, redirect_uri)
    if row["client_id"] != client.client_id
      return oidc_token_error("invalid_grant", "Code was issued to a different client", 400)
    end
    if row["redirect_uri"] != redirect_uri
      return oidc_token_error("invalid_grant", "redirect_uri does not match the authorization", 400)
    end

    challenge = row["code_challenge"].to_s
    if challenge.blank?
      return null unless client.require_pkce == true

      return oidc_token_error("invalid_grant", "PKCE is required for this client", 400)
    end

    verified = OauthAuthorizationCode.verify_pkce(challenge, row["code_challenge_method"],
                                                  params["code_verifier"].to_s)
    return null if verified

    return oidc_token_error("invalid_grant", "code_verifier does not match code_challenge", 400)
  end

  def _refresh_token_grant(client)
    presented = params["refresh_token"].to_s
    token = OauthRefreshToken.find_by_token(presented)
    if token.nil?
      return oidc_token_error("invalid_grant", "Unknown refresh token", 400)
    end

    # A rotated token being presented again means it leaked. We cannot tell the
    # legitimate holder from the attacker, so the whole family is revoked.
    if token.reused?()
      OauthRefreshToken.revoke_chain(token["chain_id"], "refresh_token_reused")

      return oidc_token_error("invalid_grant", "Refresh token was already used", 400)
    end
    if !(token.active?())
      return oidc_token_error("invalid_grant", "Refresh token is expired or revoked", 400)
    end
    if token["client_id"] != client.client_id
      return oidc_token_error("invalid_grant", "Refresh token belongs to a different client", 400)
    end

    scopes = this._refresh_scopes(token)
    return scopes["response"] unless scopes["response"].nil?

    user = User.find_by("_key", token["user_key"])
    if user.nil?
      return oidc_token_error("invalid_grant", "The user no longer exists", 400)
    end

    token.mark_rotated()

    return this._issue_tokens(client, user, scopes["scopes"], token["chain_id"], null, null)
  end

  # A refresh may narrow the scope but never widen it (RFC 6749 §6).
  def _refresh_scopes(token)
    granted = token.scopes()
    requested = oidc_scope_list(params["scope"])
    return { "response": null, "scopes": granted } if requested.length() == 0

    escalated = requested.filter(fn(scope) !granted.includes?(scope))
    if escalated.length() != 0
      return { "response": oidc_token_error("invalid_scope",
        "Requested scope exceeds the original grant: #{escalated.join(", ")}", 400) }
    end

    return { "response": null, "scopes": requested }
  end

  # --- issuing ---------------------------------------------------------------

  def _issue_tokens(client, user, scopes, chain_id, nonce, auth_time)
    jti = uuid_v4()
    access_token = oidc_access_token(user["_key"], client.client_id, scopes, jti)

    body = {
      "access_token": access_token,
      "token_type": "Bearer",
      "expires_in": OIDC_ACCESS_TOKEN_TTL,
      "scope": scopes.join(" ")
    }

    if scopes.includes?("openid")
      body["id_token"] = oidc_id_token(user, client.client_id, scopes, nonce, auth_time,
                                       access_token)
    end

    # Only hand out a refresh token when the client asked for offline access —
    # a long-lived credential nobody requested is pure liability.
    if scopes.includes?("offline_access") && client.supports_grant?("refresh_token")
      body["refresh_token"] = OauthRefreshToken.issue(chain_id, client.client_id, user["_key"],
                                                      scopes, jti)
    end

    return oidc_json(body, 200)
  end

  # --- client authentication -------------------------------------------------

  # `client_secret_basic` then `client_secret_post`. Presenting both is an
  # error: RFC 6749 §2.3 forbids using more than one method, and accepting the
  # combination invites confusion about which one was actually checked.
  def _authenticate_client
    basic = this._basic_credentials()
    post_id = params["client_id"].to_s
    post_secret = params["client_secret"].to_s

    if !basic.nil? && post_secret.present?
      return { "response": oidc_token_error("invalid_client",
        "Use only one client authentication method", 400) }
    end

    client_id = basic.nil? ? post_id : basic["client_id"]
    secret = basic.nil? ? post_secret : basic["client_secret"]

    client = OauthClient.find_active(client_id)
    if client.nil?
      return { "response": this._client_auth_failure(!basic.nil?, "Unknown client") }
    end

    return this._verify_secret(client, secret, !basic.nil?)
  end

  def _verify_secret(client, secret, used_basic)
    if client.public?()
      # A public client has no secret; one turning up means the caller is
      # confused about which client it is, and that is worth rejecting.
      if secret.present?
        return { "response": oidc_token_error("invalid_client",
          "Public clients must not send a client_secret", 400) }
      end

      return { "response": null, "client": client }
    end

    if !(client.authenticate_secret(secret))
      return { "response": this._client_auth_failure(used_basic, "Invalid client credentials") }
    end

    return { "response": null, "client": client }
  end

  # RFC 6749 §5.2: a failed *Basic* authentication is a 401 carrying
  # WWW-Authenticate; the same failure via form parameters is a plain 400.
  def _client_auth_failure(used_basic, description)
    return oidc_token_error("invalid_client", description, 400) unless used_basic

    return {
      "status": 401,
      "headers": {
        "Content-Type": "application/json;charset=UTF-8",
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
        "WWW-Authenticate": "Basic realm=\"oauth\""
      },
      "body": { "error": "invalid_client", "error_description": description }.to_json()
    }
  end

  # Decode `Authorization: Basic base64(client_id:client_secret)`. Header names
  # arrive lowercased.
  def _basic_credentials
    header = req["headers"]["authorization"].to_s
    return null unless header.starts_with("Basic ")

    decoded = Base64.decode(header.substring(6, header.length()).trim()).to_s rescue ""
    return null unless decoded.contains(":")

    parts = decoded.split(":")

    return {
      "client_id": url_decode(parts[0]),
      "client_secret": url_decode(parts.slice(1, parts.length()).join(":"))
    }
  end
end
