# OpenID Connect helpers — generated by `soli generate oidc_provider`.
#
# Lives in app/services/ because that is loaded into the global scope
# alongside models, so controllers can call these. app/helpers/ is only
# visible to view templates.
#
# Response builders, JWK export and token minting. Kept out of the controllers
# so the error shapes are defined once: RFC 6749 is specific about which
# failures redirect back to the client and which must not, and getting that
# wrong is how an authorization endpoint becomes an open redirect.

# --- Responses ---------------------------------------------------------------

# JSON with the no-store headers RFC 6749 §5.1 requires on token responses.
# `render_json` cannot be used: it writes a fast-path response whose headers
# are fixed, so there is no way to add Cache-Control.
fn oidc_json(body_hash, status)
  return {
    "status": status,
    "headers": {
      "Content-Type": "application/json;charset=UTF-8",
      "Cache-Control": "no-store",
      "Pragma": "no-cache"
    },
    "body": body_hash.to_json()
  }
end

# An OAuth error at the *token* endpoint: always JSON, never a redirect.
fn oidc_token_error(code, description, status)
  body = { "error": code }
  body["error_description"] = description unless description.blank?

  return oidc_json(body, status)
end

# An OAuth error at the *authorization* endpoint that is safe to hand back to
# the client, because the redirect_uri was validated first.
#
# Never call this before validating client_id and redirect_uri — redirecting to
# an unvalidated URI is precisely the open redirect RFC 6749 §4.1.2.1 carves
# these errors out to prevent. Use `oidc_authorize_fatal` for that case.
fn oidc_authorize_error(redirect_uri, code, description, state)
  location = "#{redirect_uri}#{oidc_query_separator(redirect_uri)}error=#{url_encode(code)}"
  location = "#{location}&error_description=#{url_encode(description)}" unless description.blank?
  location = "#{location}&state=#{url_encode(state.to_s)}" unless state.blank?

  return redirect_external(location)
end

# An error we must NOT redirect for: the client is unknown, or the redirect_uri
# is not one it registered. Rendered in place, as a plain page.
fn oidc_authorize_fatal(message)
  return render("oauth_authorizations/error", { "message": message }, { "status": 400 })
end

# A registered redirect_uri may already carry a query string, and RFC 6749
# §3.1.2 requires parameters to be appended rather than replace it.
fn oidc_query_separator(uri)
  return "&" if uri.to_s.contains("?")

  return "?"
end

# --- Encoding ----------------------------------------------------------------

# Crypto.* speaks hex; JOSE speaks unpadded base64url. Decode to raw bytes
# before encoding — base64url of the hex *text* is a different, wrong value of
# twice the length.
fn oidc_b64_digest(hex_digest)
  return Base64.urlsafe_encode(Hex.decode(hex_digest))
end

# --- Keys --------------------------------------------------------------------

# One JWKS entry for a public PEM, or nil when the PEM is unset.
fn oidc_jwk(public_pem)
  return null if public_pem.blank?

  key = RsaKey.public_from_pem(public_pem) rescue null
  return null if key.nil?

  return {
    "kty": "RSA",
    "use": "sig",
    "alg": "RS256",
    "kid": oidc_kid(public_pem),
    "n": Base64.urlsafe_encode(Hex.decode(key["n"])),
    "e": Base64.urlsafe_encode(Hex.decode(key["e"]))
  }
end

# --- Tokens ------------------------------------------------------------------

# Mint the id_token. `access_token` is used for the at_hash binding, which lets
# a client detect an access token swapped in from a different response.
fn oidc_id_token(user, client_id, scopes, nonce, auth_time, access_token)
  claims = oidc_user_claims(user, scopes)
  claims["sub"] = user["_key"]

  options = {
    "algorithm": "RS256",
    "key": oidc_private_key(),
    "kid": oidc_active_kid(),
    "iss": oidc_issuer(),
    "aud": client_id,
    "expires_in": OIDC_ID_TOKEN_TTL
  }
  claims["nonce"] = nonce unless nonce.blank?
  claims["auth_time"] = auth_time unless auth_time.nil?
  claims["at_hash"] = oidc_at_hash(access_token) unless access_token.blank?

  return jwt_sign(claims, "", options)
end

# Left-most 128 bits of the SHA-256 of the access token, base64url (OIDC Core
# §3.1.3.6).
fn oidc_at_hash(access_token)
  return Base64.urlsafe_encode(Hex.decode(Crypto.sha256(access_token)).take(16))
end

# Mint an access token. RFC 9068 profile: `at+jwt` typed, with the scope and a
# `jti` so it can be denylisted before it expires.
fn oidc_access_token(user_key, client_id, scopes, jti)
  options = {
    "algorithm": "RS256",
    "key": oidc_private_key(),
    "kid": oidc_active_kid(),
    "typ": "at+jwt",
    "iss": oidc_issuer(),
    "aud": client_id,
    "jti": jti,
    "expires_in": OIDC_ACCESS_TOKEN_TTL
  }

  return jwt_sign({ "sub": user_key, "scope": scopes.join(" ") }, "", options)
end

# Verify an access token presented as a Bearer credential. Returns the claims,
# or nil when the token is invalid, expired or revoked.
fn oidc_verify_access_token(token)
  return null if token.blank?

  # `jwt_verify` reports most failures as `{error: true, ...}` but *raises* when
  # the token is malformed enough that the header will not parse — which is
  # exactly what an attacker sends. Both have to be caught, or a garbage bearer
  # token becomes a 500 instead of a 401.
  claims = jwt_verify(token, "", {
    "algorithm": "RS256",
    "key": oidc_public_key(),
    "issuer": oidc_issuer()
  }) rescue null
  return null if claims.nil?
  return null if claims["error"] == true
  return null if OauthRevocation.revoked?(claims["jti"])

  return claims
end

# Pull a Bearer token out of the Authorization header. Header names arrive
# lowercased.
fn oidc_bearer_token(req)
  header = req["headers"]["authorization"].to_s
  return "" unless header.starts_with("Bearer ")

  return header.substring(7, header.length()).trim()
end

# Human-readable scope text for the consent screen. A user cannot make a
# meaningful decision about a raw scope name, so anything you add to
# OIDC_SUPPORTED_SCOPES should get a sentence here too.
fn scope_description(scope)
  return "Confirm your identity" if scope == "openid"
  return "See your name and profile details" if scope == "profile"
  return "See your email address" if scope == "email"
  return "Stay signed in when you are away" if scope == "offline_access"

  return scope.to_s
end

fn oidc_scope_list(scope_string)
  return [] if scope_string.blank?

  return scope_string.to_s.trim().split(" ").filter(fn(s) s.present?)
end
