# Discovery + JWKS — generated by `soli generate oidc_provider`.
#
# These two documents are how a relying party configures itself: the discovery
# document says where the endpoints are and what this provider supports, and
# the JWKS says which keys sign its tokens.

class OidcDiscoveryController < Controller
  # GET /.well-known/openid-configuration
  #
  # Only advertise what is actually implemented. A provider that claims a flow
  # it does not support sends clients down a path that fails at the token
  # endpoint, which is far harder to diagnose than an honest omission.
  def openid_configuration
    issuer = oidc_issuer()
    document = {
      "issuer": issuer,
      "authorization_endpoint": "#{issuer}/oauth/authorize",
      "token_endpoint": "#{issuer}/oauth/token",
      "userinfo_endpoint": "#{issuer}/oauth/userinfo",
      "jwks_uri": "#{issuer}/.well-known/jwks.json",
      "revocation_endpoint": "#{issuer}/oauth/revoke",
      "end_session_endpoint": "#{issuer}/oauth/logout",
      "scopes_supported": OIDC_SUPPORTED_SCOPES,
      "response_types_supported": ["code"],
      "response_modes_supported": ["query"],
      "grant_types_supported": ["authorization_code", "refresh_token"],
      "subject_types_supported": ["public"],
      "id_token_signing_alg_values_supported": ["RS256"],
      "token_endpoint_auth_methods_supported": [
        "client_secret_basic", "client_secret_post", "none"
      ],
      "code_challenge_methods_supported": ["S256"],
      "claims_supported": [
        "sub", "iss", "aud", "exp", "iat", "nonce", "auth_time", "at_hash",
        "name", "preferred_username", "email", "email_verified"
      ]
    }

    return {
      "status": 200,
      "headers": {
        "Content-Type": "application/json;charset=UTF-8",
        "Cache-Control": "public, max-age=3600"
      },
      "body": document.to_json()
    }
  end

  # GET /.well-known/jwks.json
  #
  # Lists the active key and, during a rotation, the previous one — so tokens
  # signed just before the rollover still verify. Signing always uses the
  # active key alone.
  def jwks
    keys = [oidc_jwk(oidc_public_key()), oidc_jwk(oidc_previous_public_key())]

    return {
      "status": 200,
      "headers": {
        "Content-Type": "application/jwk-set+json",
        "Cache-Control": "public, max-age=3600"
      },
      "body": { "keys": keys.filter(fn(key) !key.nil?) }.to_json()
    }
  end
end
