# Auth view helpers — generated by `soli generate auth`.
#
# View templates run in their own scope and can only call helpers + builtins,
# so `current_user` / `signed_in?` are defined here for use in .slv views
# (e.g. `<% if signed_in? %>`). Controllers and policies use the matching
# globals in app/policies/application_policy.sl.

def current_user
  return req["current_user"] rescue null
end

def signed_in?
  return !current_user().nil?
end
