# Auth mailer — password reset + email confirmation. Generated by `soli generate auth`.
#
# Bodies render app/views/auth_mailer/<action>.html.slv. Configure delivery
# via SOLI_SMTP_* env vars or Mailer.configure({...}); set
# SOLI_MAIL_DELIVERY_METHOD=logger in dev to print emails to the console.
# Links are built from `auth_base_url` (app/models/user.sl).

class AuthMailer < Mailer
  def reset_password(user, token)
    @user = user
    @reset_url = auth_base_url() + "/password/edit?token=" + token
    return this.mail(to: user.email, subject: "Reset your password")
  end

  def confirm_email(user, token)
    @user = user
    @confirm_url = auth_base_url() + "/confirm_email?token=" + token
    return this.mail(to: user.email, subject: "Confirm your email address")
  end
end
