# Confirmations controller — email confirmation. Generated by `soli generate auth`.
#
# Signup sends a confirmation link (see RegistrationsController); this
# controller confirms it and can resend a fresh one. The resend form always
# responds the same way whether or not the email exists.

class ConfirmationsController < Controller
  static {
    this.layout = "application"
  }

  # GET /confirm_email?token=... — the link from the email
  def show
    token = params["token"].to_s
    let user = null
    user = User.find_by("confirmation_token_digest", Crypto.sha256(token)) unless token.blank?
    if user.nil?
      return render("confirmations/new", {
        "title": "Confirm your email",
        "notice": "",
        "error": "That confirmation link is invalid or was already used. Enter your email to get a fresh one."
      })
    end

    user.confirm_email()
    # Confirmed — sign the user straight in.
    session_regenerate()
    session_set("user_id", user["_key"])
    return redirect("/")
  end

  # GET /confirmation/resend
  def new
    render("confirmations/new", { "title": "Confirm your email", "notice": "", "error": "" })
  end

  # POST /confirmation/resend
  def create
    email = params["email"].to_s.trim().downcase()
    user = User.find_by("email", email)
    if !user.nil? && !user.confirmed?()
      token = user.start_email_confirmation()
      AuthMailer.confirm_email(user, token).deliver_now() rescue null
    end

    return render("confirmations/new", {
      "title": "Confirm your email",
      "notice": "If that email needs confirming, a fresh link is on its way.",
      "error": ""
    })
  end
end
