# Confirmations controller — email confirmation. Generated by `soli generate auth`.
#
# Signup sends a confirmation link (see RegistrationsController); this
# controller confirms it and can resend a fresh one. The resend form always
# responds the same way whether or not the email exists.

class ConfirmationsController < Controller
  static {
    this.layout = "application"
  }

  # GET /confirm_email?token=... — the link from the email
  def show
    token = params["token"].to_s
    let user = null
    user = User.find_by("confirmation_token_digest", Crypto.sha256(token)) unless token.blank?
    # An expired link is indistinguishable from an invalid one to the visitor,
    # which is right: both mean "ask for a fresh one".
    user = null if !user.nil? && user.confirmation_token_expired?()
    if user.nil?
      return render(
        "confirmations/new",
        {
          "title": "Confirm your email",
          "notice": "",
          "error": "That confirmation link is invalid or was already used. Enter your email to get a fresh one."
        }
      )
    end

    user.confirm_email()
    # Confirm, but do not sign in.
    #
    # This is a GET reached from an email, so whoever (or whatever) follows the
    # link gets the session: a corporate link scanner, a shared mailbox, or the
    # colleague the message was forwarded to. Confirming the address from a link
    # is fine; handing out a logged-in session from one is not. The visitor
    # signs in normally, which is one form fill and proves they hold the
    # password.
    return render(
      "confirmations/new",
      {
        "title": "Email confirmed",
        "notice": "Your email address is confirmed. Sign in to continue.",
        "error": ""
      }
    )
  end

  # GET /confirmation/resend
  def new
    render(
      "confirmations/new",
      {
        "title": "Confirm your email",
        "notice": "",
        "error": ""
      }
    )
  end

  # POST /confirmation/resend
  def create
    email = params["email"].to_s.trim().downcase()
    user = User.find_by("email", email)
    if !user.nil? && !user.confirmed?()
      token = user.start_email_confirmation()
      AuthMailer.confirm_email(user, token).deliver_now() rescue null
    end

    return render(
      "confirmations/new",
      {
        "title": "Confirm your email",
        "notice": "If that email needs confirming, a fresh link is on its way.",
        "error": ""
      }
    )
  end
end
