# Load the current user — generated by `soli generate auth`.
#
# Runs on every request (low order so it lands before app middleware). Reads
# the signed-in user id from the session and loads the User record into
# `req["current_user"]`, which `current_user()` / `authorize()` read. Guests
# leave it nil. This never blocks the request — gating is the job of policies
# and the `require_login` pattern, not this loader.

# order: 5

def load_current_user(req)
  user_id = session_get("user_id")
  if !user_id.blank?
    req["current_user"] = User.find_by("_key", user_id) rescue null
  end
  return { "continue": true, "request": req }
end
