# Passwords controller — the "forgot password" flow. Generated by `soli generate auth`.
#
# POST /password/reset always responds the same way whether or not the email
# exists, so the form can't be used to probe for accounts. Reset links carry
# a one-time token whose SHA-256 digest is stored; links expire after
# AUTH_RESET_TOKEN_TTL seconds (see app/models/user.sl).

class PasswordsController < Controller
  static {
    this.layout = "application"
  }

  # GET /password/reset — request a reset link
  def new
    render("passwords/new", { "title": "Reset password", "notice": "", "error": "" })
  end

  # POST /password/reset — send the link
  def create
    email = params["email"].to_s.trim().downcase()
    user = User.find_by("email", email)
    if !user.nil?
      token = user.start_password_reset()
      AuthMailer.reset_password(user, token).deliver_now() rescue null
    end

    return render("passwords/new", {
      "title": "Reset password",
      "notice": "If that email exists, a reset link is on its way.",
      "error": ""
    })
  end

  # GET /password/edit?token=... — the form behind the emailed link
  def edit
    user = this.user_for_token(params["token"])
    if user.nil?
      return render("passwords/new", {
        "title": "Reset password",
        "notice": "",
        "error": "That reset link is invalid or has expired. Request a new one."
      })
    end

    return render("passwords/edit", {
      "title": "Choose a new password",
      "token": params["token"].to_s,
      "error": ""
    })
  end

  # POST /password/update
  def update
    user = this.user_for_token(params["token"])
    if user.nil?
      return render("passwords/new", {
        "title": "Reset password",
        "notice": "",
        "error": "That reset link is invalid or has expired. Request a new one."
      })
    end

    password = params["password"].to_s
    if password.length() < 8
      return render("passwords/edit", {
        "title": "Choose a new password",
        "token": params["token"].to_s,
        "error": "Password must be at least 8 characters."
      })
    end
    if password != params["password_confirmation"].to_s
      return render("passwords/edit", {
        "title": "Choose a new password",
        "token": params["token"].to_s,
        "error": "Passwords don't match."
      })
    end

    user.finish_password_reset(password)
    # Sign the user straight in with a fresh session.
    session_regenerate()
    session_set("user_id", user["_key"])
    return redirect("/")
  end

  # Resolve a reset token to its (non-expired) user, or nil.
  def user_for_token(token)
    return null if token.blank?

    user = User.find_by("reset_token_digest", Crypto.sha256(token.to_s))
    return null if user.nil?
    return null if user.reset_token_expired?()
    return user
  end
end
