# Passwords controller — the "forgot password" flow. Generated by `soli generate auth`.
#
# POST /password/reset always responds the same way whether or not the email
# exists, so the form can't be used to probe for accounts. Reset links carry
# a one-time token whose SHA-256 digest is stored; links expire after
# AUTH_RESET_TOKEN_TTL seconds (see app/models/user.sl).

class PasswordsController < Controller
  static {
    this.layout = "application"
  }

  # GET /password/reset — request a reset link
  def new
    render(
      "passwords/new",
      {
        "title": "Reset password",
        "notice": "",
        "error": ""
      }
    )
  end

  # POST /password/reset — send the link
  def create
    # Throttle per source address. The uniform response below stops this
    # endpoint being used to probe for accounts, but nothing stopped it being
    # used to mail-bomb one known address (or to burn the app's sending
    # reputation across many).
    limiter = rate_limiter_from_ip(req, AUTH_ATTEMPTS_PER_IP, AUTH_IP_WINDOW_SECONDS)
    unless limiter.allowed()
      return render(
        "passwords/new",
        {
          "title": "Reset password",
          "notice": "",
          "error": "Too many reset requests. Try again in a few minutes."
        },
        {"status": 429}
      )
    end

    email = params["email"].to_s.trim().downcase()
    user = User.find_by("email", email)
    if !user.nil?
      token = user.start_password_reset()
      AuthMailer.reset_password(user, token).deliver_now() rescue null
    end

    return render(
      "passwords/new",
      {
        "title": "Reset password",
        "notice": "If that email exists, a reset link is on its way.",
        "error": ""
      }
    )
  end

  # GET /password/edit?token=... — the form behind the emailed link
  def edit
    user = this.user_for_token(params["token"])
    if user.nil?
      return render(
        "passwords/new",
        {
          "title": "Reset password",
          "notice": "",
          "error": "That reset link is invalid or has expired. Request a new one."
        }
      )
    end

    return render(
      "passwords/edit",
      {
        "title": "Choose a new password",
        "token": params["token"].to_s,
        "error": ""
      }
    )
  end

  # POST /password/update
  def update
    user = this.user_for_token(params["token"])
    if user.nil?
      return render(
        "passwords/new",
        {
          "title": "Reset password",
          "notice": "",
          "error": "That reset link is invalid or has expired. Request a new one."
        }
      )
    end

    password = params["password"].to_s
    # One rule, one place: `password_error` is what sign-up enforces too, so
    # the reset flow can't quietly become the way to install a weaker password
    # than registration would have accepted.
    password_error = user.password_error(password)
    return this._reject_edit(password_error) unless password_error.nil?

    return this._reject_edit("Passwords don't match.") if password != params["password_confirmation"].to_s

    user.finish_password_reset(password)
    # Sign the user straight in with a fresh session.
    session_regenerate()
    session_set("user_id", user["_key"])
    # Stamped so a later password reset can invalidate this session.
    session_set("session_version", user.current_session_version())
    return redirect("/")
  end

  # Re-render the "choose a new password" form with an error, keeping the
  # token so the user doesn't have to click the emailed link again.
  def _reject_edit(message)
    return render(
      "passwords/edit",
      {
        "title": "Choose a new password",
        "token": params["token"].to_s,
        "error": message
      },
      {"status": 422}
    )
  end

  # Resolve a reset token to its (non-expired) user, or nil.
  def user_for_token(token)
    return null if token.blank?

    user = User.find_by("reset_token_digest", Crypto.sha256(token.to_s))
    return null if user.nil?
    return null if user.reset_token_expired?()
    return user
  end
end
