# Registrations controller — sign up. Generated by `soli generate auth`.
#
# New accounts get a confirmation email (AuthMailer). Whether an unconfirmed
# account may sign in is controlled by `auth_require_confirmed_email` in
# app/models/user.sl (off by default so the flow works before SMTP is set up).

class RegistrationsController < Controller
  static {
    this.layout = "application"
  }

  # GET /signup
  def new
    render("registrations/new", { "title": "Create account", "error": "", "user": User.new() })
  end

  # POST /signup
  def create
    user = User.new()
    user.email = params["email"]
    user.set_password(params["password"].to_s)
    user.save()
    if user._errors
      return render("registrations/new", {
        "title": "Create account",
        "user": user,
        "error": "Could not create your account"
      })
    end

    # Send the confirmation link. `rescue null` keeps signup working before
    # SMTP is configured (set SOLI_MAIL_DELIVERY_METHOD=logger in dev to see
    # the email in the console instead).
    token = user.start_email_confirmation()
    AuthMailer.confirm_email(user, token).deliver_now() rescue null

    if auth_require_confirmed_email()
      return render("sessions/new", {
        "title": "Sign in",
        "error": "Account created — confirm your email to sign in.",
        "email": user.email
      })
    end

    session_regenerate()
    session_set("user_id", user["_key"])
    return redirect("/")
  end
end
