# Registrations controller — sign up. Generated by `soli generate auth`.

class RegistrationsController < Controller
  static {
    this.layout = "application"
  }

  # GET /signup
  def new
    render("registrations/new", { "title": "Create account", "error": "", "user": User.new() })
  end

  # POST /signup
  def create
    user = User.new()
    user.email = params["email"]
    user.set_password(params["password"].to_s)
    user.save()
    if user._errors
      return render("registrations/new", {
        "title": "Create account",
        "user": user,
        "error": "Could not create your account"
      })
    end

    session_regenerate()
    session_set("user_id", user["_key"])
    return redirect("/")
  end
end
