# Registrations controller — sign up. Generated by `soli generate auth`.
#
# New accounts get a confirmation email (AuthMailer). Whether an unconfirmed
# account may sign in is controlled by `auth_require_confirmed_email` in
# app/models/user.sl (off by default so the flow works before SMTP is set up).

class RegistrationsController < Controller
  static {
    this.layout = "application"
  }

  # GET /signup
  def new
    render(
      "registrations/new",
      {
        "title": "Create account",
        "error": "",
        "user": User.new()
      }
    )
  end

  # POST /signup
  def create
    user = User.new()
    user.email = params["email"]

    # Throttle account creation per source address: unmetered sign-up is how
    # an app ends up seeding spam, and it is also a cheap Argon2id CPU sink
    # (every attempt costs the server ~100ms of hashing).
    limiter = rate_limiter_from_ip(req, AUTH_ATTEMPTS_PER_IP, AUTH_IP_WINDOW_SECONDS)
    unless limiter.allowed()
      return this._reject(user, "Too many sign-up attempts. Try again in a few minutes.", 429)
    end

    # `set_password` is a no-op on a blank value (so profile saves don't wipe
    # the digest), which means the length rule has to be checked here or an
    # account can be created with no usable password at all.
    password_error = user.password_error(params["password"])
    return this._reject(user, password_error, 422) unless password_error.nil?

    user.set_password(params["password"].to_s)
    user.save()
    return this._reject(user, "Could not create your account", 422) if user._errors

    # Send the confirmation link. `rescue null` keeps signup working before
    # SMTP is configured (set SOLI_MAIL_DELIVERY_METHOD=logger in dev to see
    # the email in the console instead).
    token = user.start_email_confirmation()
    AuthMailer.confirm_email(user, token).deliver_now() rescue null

    if auth_require_confirmed_email()
      return render(
        "sessions/new",
        {
          "title": "Sign in",
          "error": "Account created — confirm your email to sign in.",
          "email": user.email
        }
      )
    end

    session_regenerate()
    session_set("user_id", user["_key"])
    # Stamped so a later password reset can invalidate this session.
    session_set("session_version", user.current_session_version())
    return redirect("/")
  end

  # Re-render the sign-up form with an error and an accurate status code.
  def _reject(user, message, status)
    return render(
      "registrations/new",
      {
        "title": "Create account",
        "user": user,
        "error": message
      },
      {"status": status}
    )
  end
end
