# Sessions controller — login + logout. Generated by `soli generate auth`.

class SessionsController < Controller
  static {
    this.layout = "application"
  }

  # GET /login
  def new
    render("sessions/new", { "title": "Sign in", "error": "", "email": "" })
  end

  # POST /login
  def create
    email = (params["email"] ?? "").trim().downcase()
    password = params["password"] ?? ""
    user = User.find_by("email", email)
    if !user.nil? && user.authenticate(password)
      # New session id after a successful login defeats session fixation.
      session_regenerate()
      session_set("user_id", user["_key"])
      return redirect("/")
    end

    return render("sessions/new", {
      "title": "Sign in",
      "error": "Invalid email or password",
      "email": email
    })
  end

  # DELETE /logout
  def destroy
    session_destroy()
    return redirect("/login")
  end
end
