# Sessions controller — login + logout. Generated by `soli generate auth`.
#
# Ships with account lockout (AUTH_MAX_FAILED_ATTEMPTS wrong passwords lock
# the account for AUTH_LOCKOUT_SECONDS), optional remember-me (persistent
# HttpOnly cookie), and an optional confirmed-email gate (flip
# `auth_require_confirmed_email` in app/models/user.sl).

class SessionsController < Controller
  static {
    this.layout = "application"
  }

  # GET /login
  def new
    render("sessions/new", { "title": "Sign in", "error": "", "email": "" })
  end

  # POST /login
  def create
    email = params["email"].to_s.trim().downcase()
    password = params["password"].to_s
    user = User.find_by("email", email)

    if !user.nil? && user.locked?()
      return render("sessions/new", {
        "title": "Sign in",
        "error": "Account locked after too many failed attempts. Try again later or reset your password.",
        "email": email
      })
    end

    if !user.nil? && user.authenticate(password)
      if auth_require_confirmed_email() && !user.confirmed?()
        return render("sessions/new", {
          "title": "Sign in",
          "error": "Please confirm your email address first — check your inbox.",
          "email": email
        })
      end

      user.clear_failed_attempts()
      # New session id after a successful login defeats session fixation.
      session_regenerate()
      session_set("user_id", user["_key"])

      if params["remember_me"].to_s == "1"
        token = user.start_remember_me()
        set_cookie("remember_token", user["_key"] + ":" + token, {
          "max_age": AUTH_REMEMBER_DAYS * 86400,
          "http_only": true,
          "same_site": "Lax"
        })
      end

      return redirect("/")
    end

    user.register_failed_attempt() unless user.nil?
    return render("sessions/new", {
      "title": "Sign in",
      "error": "Invalid email or password",
      "email": email
    })
  end

  # DELETE /logout
  def destroy
    user_id = session_get("user_id")
    if !user_id.blank?
      user = User.find_by("_key", user_id) rescue null
      user&.forget_me()
    end
    # Expire the remember-me cookie immediately.
    set_cookie("remember_token", "", { "max_age": 0, "http_only": true })
    session_destroy()
    return redirect("/login")
  end
end
