# Sessions controller — login + logout. Generated by `soli generate auth`.
#
# Ships with a per-IP throttle (AUTH_ATTEMPTS_PER_IP per
# AUTH_IP_WINDOW_SECONDS), account lockout (AUTH_MAX_FAILED_ATTEMPTS wrong
# passwords lock the account for AUTH_LOCKOUT_SECONDS), optional remember-me
# (persistent HttpOnly + Secure cookie), and an optional confirmed-email gate
# (flip `auth_require_confirmed_email` in app/models/user.sl).
#
# The failure paths are deliberately uniform in both wording and cost: an
# unknown address and a wrong password produce the same message and the same
# response time, so sign-in cannot be used to enumerate accounts.

class SessionsController < Controller
  static {
    this.layout = "application"
  }

  # GET /login
  def new
    render(
      "sessions/new",
      {
        "title": "Sign in",
        "error": "",
        "email": ""
      }
    )
  end

  # POST /login
  def create
    email = params["email"].to_s.trim().downcase()
    password = params["password"].to_s

    # First gate: how many sign-in attempts this source address gets. The
    # per-account lockout below is blind to credential stuffing (one guess
    # each against thousands of accounts) and it is itself abusable as a
    # denial of service against a known address. This closes both.
    limiter = rate_limiter_from_ip(req, AUTH_ATTEMPTS_PER_IP, AUTH_IP_WINDOW_SECONDS)
    unless limiter.allowed()
      return this._reject("Too many sign-in attempts. Try again in a few minutes.", email, 429)
    end

    user = User.find_by("email", email)

    # Both branches must cost the same. `authenticate` runs Argon2id (~100ms);
    # bailing out on a missing account would return in microseconds, and that
    # difference is a reliable "is this address registered?" oracle no matter
    # how carefully the error message is worded.
    authenticated = user.nil? ? User.burn_password_work(password) : user.authenticate(password)

    unless authenticated
      user.register_failed_attempt() unless user.nil?
      return this._reject("Invalid email or password", email, 401)
    end

    # Everything below here has already proved knowledge of the password, so a
    # specific message leaks nothing an attacker doesn't have. This is why the
    # lockout check sits *after* verification rather than before it: a locked
    # account must be indistinguishable from a wrong password to someone who
    # doesn't know the password, and self-explanatory to the owner who does.
    if user.locked?()
      return this._reject(
        "Account locked after too many failed attempts. Try again later or reset your password.",
        email,
        403
      )
    end

    if auth_require_confirmed_email() && !user.confirmed?()
      return this._reject("Please confirm your email address first — check your inbox.", email, 403)
    end

    user.clear_failed_attempts()
    # New session id after a successful login defeats session fixation.
    session_regenerate()
    session_set("user_id", user["_key"])

    if params["remember_me"].to_s == "1"
      token = user.start_remember_me()
      # `secure` matters more here than on the session cookie: this one is a
      # 30-day bearer credential, and without the flag a single plaintext
      # request to the same host hands it to anyone on the path.
      set_cookie("remember_token", user["_key"] + ":" + token, {
        "max_age": AUTH_REMEMBER_DAYS * 86400,
        "http_only": true,
        "same_site": "Lax",
        "secure": true
      })
    end

    return redirect("/")
  end

  # Re-render the sign-in form with an error and an accurate status code.
  # Every failure path goes through here so none of them can drift into
  # leaking more than the others.
  def _reject(message, email, status)
    return render(
      "sessions/new",
      {
        "title": "Sign in",
        "error": message,
        "email": email
      },
      {"status": status}
    )
  end

  # DELETE /logout
  def destroy
    user_id = session_get("user_id")
    if !user_id.blank?
      user = User.find_by("_key", user_id) rescue null
      user&.forget_me()
    end
    # Expire the remember-me cookie immediately.
    set_cookie("remember_token", "", {
      "max_age": 0,
      "http_only": true,
      "same_site": "Lax",
      "secure": true
    })
    session_destroy()
    return redirect("/login")
  end
end
