# User model — generated by `soli generate auth`.
# Collection: users
#
# Passwords are never stored in plaintext: assign through `set_password`,
# which hashes with Argon2id (the built-in Crypto module), and verify with
# `authenticate`. Reset/confirmation/remember tokens are random UUIDs whose
# SHA-256 digest is stored — a database leak can't be replayed as a live link.

# --- Auth flow tuning --------------------------------------------------------
const AUTH_RESET_TOKEN_TTL = 7200  # password-reset links live 2 hours
const AUTH_MAX_FAILED_ATTEMPTS = 10  # failed logins before lockout
const AUTH_LOCKOUT_SECONDS = 1800  # auto-unlock after 30 minutes
const AUTH_REMEMBER_DAYS = 30  # remember-me cookie lifetime
const AUTH_MIN_PASSWORD_LENGTH = 12  # shortest password accepted at sign-up

# Per-IP throttle on the credential endpoints (login, sign-up, reset). The
# per-account lockout above cannot see these two attacks: credential stuffing
# spread thinly across thousands of accounts never trips it, and an attacker
# who knows an email address can lock its owner out on demand. Keying on the
# source address covers both.
const AUTH_ATTEMPTS_PER_IP = 15
const AUTH_IP_WINDOW_SECONDS = 300

# Base URL used in password-reset / confirmation emails.
#
# Read from the environment so a deployment sets it once, next to its other
# config, rather than by editing this file. The literal fallback is a dev
# convenience: left in place in production it mails `http://localhost` reset
# links, which are both useless and, if the host does resolve, sent in the
# clear. Set APP_BASE_URL to your `https://` origin.
def auth_base_url
  return getenv("APP_BASE_URL").to_s if getenv("APP_BASE_URL").present?

  return "http://localhost:5011"
end

# Require a confirmed email before sign-in. Flip to true once SMTP is
# configured (SOLI_SMTP_* env vars — see the mailer docs) so users can
# actually receive the confirmation link.
def auth_require_confirmed_email
  return false
end

class User < Model
  # Fields: email, password_digest, role, plus the auth-flow fields:
  # reset_token_digest, reset_sent_at, confirmation_token_digest,
  # confirmation_sent_at, confirmed_at, remember_token_digest,
  # failed_attempts, locked_at.
  # (Model stores fields dynamically — no need to declare them.)
  validates(
    "email",
    {
      "presence": true,
      "uniqueness": true,
      "format": "email"
    }
  )
  before_save("normalize")

  def normalize
    this.email = this.email.trim().downcase() unless this.email.blank?
    this.role = "member" if this.role.blank?
  end

  # Hash `plaintext` and store it in `password_digest`. No-op when blank so a
  # profile update that doesn't change the password leaves the digest intact.
  # Callers that accept a *new* password must run `password_error` first —
  # this method deliberately has no opinion, so that a profile save with no
  # password field doesn't wipe the digest.
  def set_password(plaintext)
    return if plaintext.blank?

    this.password_digest = Crypto.password_hash(plaintext)
  end

  # Why `plaintext` is unacceptable as a new password, or null when it is fine.
  #
  # Length is the only rule here on purpose. Composition rules ("one digit,
  # one symbol") push people toward `Password1!` — they add a decimal digit of
  # real entropy and a lot of friction. Length is what actually raises the
  # cost of an offline attack against the Argon2id digest.
  def password_error(plaintext)
    value = plaintext.to_s
    return "Password is required" if value.blank?

    if value.length() < AUTH_MIN_PASSWORD_LENGTH
      return "Password must be at least #{AUTH_MIN_PASSWORD_LENGTH} characters"
    end
    return null
  end

  # True when `plaintext` matches the stored Argon2id digest.
  def authenticate(plaintext)
    return false if this.password_digest.blank?

    return Crypto.password_verify(plaintext, this.password_digest)
  end

  # Spend the same Argon2id work as a real `authenticate` without having an
  # account to check against. Sign-in calls this when no user matches the
  # submitted email: verifying costs ~100ms and returning early costs none, so
  # without it the response time alone tells an attacker which addresses are
  # registered — a user-enumeration oracle that no error-message wording can
  # close. The result is deliberately discarded.
  static def burn_password_work(plaintext)
    Crypto.password_hash(plaintext.to_s)
    return false
  end

  def admin?
    return this.role == "admin"
  end

  # --- Password reset ---------------------------------------------------------

  # Issue a reset token: returns the plaintext token (goes into the email);
  # only its digest is stored.
  def start_password_reset
    token = uuid_v4()
    this.reset_token_digest = Crypto.sha256(token)
    this.reset_sent_at = DateTime.utc().to_unix()
    this.update()
    return token
  end

  def reset_token_expired?
    return true if this.reset_sent_at.nil?

    return DateTime.utc().to_unix() - this.reset_sent_at > AUTH_RESET_TOKEN_TTL
  end

  # Set the new password, burn the token, and clear any lockout.
  #
  # Also drops the remember-me digest. Resetting a password is what someone
  # does when they think the account is compromised, and a remember-me cookie
  # outlives it by up to AUTH_REMEMBER_DAYS — leaving it valid means the reset
  # doesn't actually evict the attacker.
  def finish_password_reset(plaintext)
    this.set_password(plaintext)
    this.reset_token_digest = null
    this.reset_sent_at = null
    this.remember_token_digest = null
    this.failed_attempts = 0
    this.locked_at = null
    return this.update()
  end

  # --- Email confirmation -----------------------------------------------------
  def start_email_confirmation
    token = uuid_v4()
    this.confirmation_token_digest = Crypto.sha256(token)
    this.confirmation_sent_at = DateTime.utc().to_unix()
    this.update()
    return token
  end

  def confirm_email
    this.confirmed_at = DateTime.utc().to_unix()
    this.confirmation_token_digest = null
    return this.update()
  end

  def confirmed?
    return !this.confirmed_at.nil?
  end

  # --- Remember me ------------------------------------------------------------
  def start_remember_me
    token = uuid_v4()
    this.remember_token_digest = Crypto.sha256(token)
    this.update()
    return token
  end

  def forget_me
    return true if this.remember_token_digest.blank?

    this.remember_token_digest = null
    return this.update()
  end

  def remembered_by?(token)
    return false if this.remember_token_digest.blank?

    return Crypto.secure_compare(Crypto.sha256(token.to_s), this.remember_token_digest)
  end

  # --- Account lockout --------------------------------------------------------
  def locked?
    return false if this.locked_at.nil?

    if DateTime.utc().to_unix() - this.locked_at > AUTH_LOCKOUT_SECONDS
      # The lockout window has passed — auto-unlock.
      this.locked_at = null
      this.failed_attempts = 0
      this.update()
      return false
    end
    return true
  end

  def register_failed_attempt
    # Don't re-stamp `locked_at` on an account that is *currently* locked:
    # doing so slides the 30-minute window forward on every further guess, so
    # an attacker who keeps knocking keeps the owner locked out indefinitely.
    # The lockout should expire on schedule no matter how loud the attack is.
    #
    # Ask `locked?()` rather than testing `locked_at` directly — it is what
    # clears an expired stamp. Testing the raw field meant that once the first
    # lockout landed, nothing on the failure path ever cleared it, so
    # `failed_attempts` froze and the account could never lock a second time:
    # after the first window elapsed the attacker guessed at full rate forever.
    return true if this.locked?()

    this.failed_attempts = (this.failed_attempts ?? 0) + 1
    this.locked_at = DateTime.utc().to_unix() if this.failed_attempts >= AUTH_MAX_FAILED_ATTEMPTS
    this.update()
  end

  def clear_failed_attempts
    attempts = this.failed_attempts ?? 0
    return if attempts == 0 && this.locked_at.nil?

    this.failed_attempts = 0
    this.locked_at = null
    this.update()
  end
end
