# Example policy — generated by `soli generate auth`.
#
# Demonstrates the conventions: admins can do anything; a user can view and
# edit their own record; nobody else can. Every rule guards on `signed_in?`
# first so a guest (nil user) is denied rather than crashing. Copy this file
# to scaffold policies for your own models.

class UserPolicy < ApplicationPolicy
  def index?
    this.admin?()
  end

  def show?
    this.owner_or_admin?()
  end

  def update?
    this.owner_or_admin?()
  end

  def create?
    this.admin?()
  end

  def destroy?
    this.admin?()
  end

  def admin?
    this.signed_in?() && this.user.admin?()
  end

  def owner_or_admin?
    return false unless this.signed_in?()

    this.user.admin?() || this.user["_key"] == this.record["_key"]
  end
end
