# User model — generated by `soli generate auth`.
# Collection: users
#
# Passwords are never stored in plaintext: assign through `set_password`,
# which hashes with Argon2id (the built-in Crypto module), and verify with
# `authenticate`.

class User < Model
  # Fields: email, password_digest, role
  # (Model stores fields dynamically — no need to declare them.)

  validates("email", { "presence": true, "uniqueness": true, "format": "email" })

  before_save("normalize")

  def normalize
    this.email = this.email.trim().downcase() unless this.email.blank?
    this.role = "member" if this.role.blank?
  end

  # Hash `plaintext` and store it in `password_digest`. No-op when blank so a
  # profile update that doesn't change the password leaves the digest intact.
  def set_password(plaintext)
    return if plaintext.blank?

    this.password_digest = Crypto.password_hash(plaintext)
  end

  # True when `plaintext` matches the stored Argon2id digest.
  def authenticate(plaintext)
    return false if this.password_digest.blank?

    return Crypto.password_verify(plaintext, this.password_digest)
  end

  def admin?
    return this.role == "admin"
  end
end
