# ============================================================================
# Cross-validation against INDEPENDENT reference implementations.
#
# Expected values were produced by:
#   - exclusive XML C14N : Python lxml  (etree.tostring method="c14n" exclusive=True)
#   - RSA-SHA256 PKCS#1v15: Python `cryptography` (key.sign(..., PKCS1v15(), SHA256()))
#
# This guards against the "author graded their own work" risk: the assertions
# below are not my own hand-derived expectations, they are byte-for-byte the
# output of widely-used, independently-maintained libraries.
# ============================================================================

describe("Xml.c14n_exclusive vs lxml", fn() {
    test("simple attribute sorting matches lxml", fn() {
        assert_eq(
            Xml.c14n_exclusive("<doc b='2' a='1'/>"),
            "<doc a=\"1\" b=\"2\"></doc>"
        );
    });

    test("unused ancestor namespace dropped, like lxml", fn() {
        let xml = "<n0:r xmlns:n0=\"http://a\" xmlns:n2=\"http://c\"><n1:e xmlns:n1=\"http://b\">x</n1:e></n0:r>";
        assert_eq(
            Xml.c14n_exclusive(xml),
            "<n0:r xmlns:n0=\"http://a\"><n1:e xmlns:n1=\"http://b\">x</n1:e></n0:r>"
        );
    });

    test("SAML-like: unused ns is pushed DOWN to where it is used (exclusive)", fn() {
        # `saml` is declared on the root but only used by <saml:Issuer>;
        # exclusive c14n renders it on Issuer, not the root. lxml output.
        let xml = "<samlp:Response xmlns:samlp=\"urn:p\" xmlns:saml=\"urn:a\" ID=\"_1\"><saml:Issuer>idp</saml:Issuer><samlp:Status><samlp:StatusCode Value=\"ok\"/></samlp:Status></samlp:Response>";
        assert_eq(
            Xml.c14n_exclusive(xml),
            "<samlp:Response xmlns:samlp=\"urn:p\" ID=\"_1\"><saml:Issuer xmlns:saml=\"urn:a\">idp</saml:Issuer><samlp:Status><samlp:StatusCode Value=\"ok\"></samlp:StatusCode></samlp:Status></samlp:Response>"
        );
    });

    test("default-namespace undeclaration matches lxml", fn() {
        assert_eq(
            Xml.c14n_exclusive("<root xmlns=\"http://a\"><child xmlns=\"\">t</child></root>"),
            "<root xmlns=\"http://a\"><child xmlns=\"\">t</child></root>"
        );
    });

    test("unprefixed attribute sorts before namespaced one, like lxml", fn() {
        assert_eq(
            Xml.c14n_exclusive("<doc xmlns:b=\"http://b\" b:z=\"1\" a=\"2\"></doc>"),
            "<doc xmlns:b=\"http://b\" a=\"2\" b:z=\"1\"></doc>"
        );
    });

    test("InclusiveNamespaces prefix list matches lxml", fn() {
        let xml = "<n0:root xmlns:n0=\"http://a\" xmlns:n2=\"http://c\"><n0:child>t</n0:child></n0:root>";
        assert_eq(
            Xml.c14n_exclusive(xml, "n2"),
            "<n0:root xmlns:n0=\"http://a\" xmlns:n2=\"http://c\"><n0:child>t</n0:child></n0:root>"
        );
    });
});

# 2048-bit key + signature generated by python `cryptography` (file-scope so
# the deferred test() closures can see them).
const N = "a36274f940c6a35ac61739580be7f238f542cc47eb561c64fe44400c8248f6947be5594312dca23b9826049a27d1c4b2e982c4a47c7d187a2eed2569270fa0d32210b5108b2a79b26f555c27f68739febfcf66dc4250cdd964743e2344800570d7bdd67ed7848404ba8e9dd1b3b2a67eaced77315983d9f1ea7e60a34dd7a3086f87079a7ad2a3a83e59a7140f7c1ae07fae201dbf65fcf1472e34f2d5afb5da8a8d8fe9e1209e9feecacfbe065af3e92daec1b548acbb938d5710818ecb26757a285d051437259bf50dbd8f570eb8032ffb0e061de261a0fbb1a05cc468093b4c32b866a29651163f9ce230abf9763db489343583584c221b9c8e2a289d0615";
const E = "010001";
const D = "8657eed704ec5065d37c452aa09f980c3d9f2f59f3a85ab0b0626e47dad923e7f3f821ed8514e6511a4a287e993f62fdba044cacf3afe8f08ea5709d8600d3bcc7c5f51c255247bef0ccbf7a1cbc1473e44425cff6b77a8bc68dce8a31491330363562a9e98c8d015664ee5fffe26604c32c7f5594c555f01560d515726c5d20c1568faaf3d92364a12b58048741a900e4ca96fa660e04a164bea00cf44bbc655000e66c19fafb2e7f47d7d55a945dc51aec8c95091804dc625defd751e9876e56933212f65b1090056fd2e946161cdf4f28862d1134a53befa6b3249c38172700c9af36d7758b86ef5407bbdb6826376fb4d3e39de514c8cd76429a80c561";
# SHA-256 DigestInfo DER prefix (RFC 8017 §9.2 notes).
const SHA256_DIGESTINFO = "3031300d060960864801650304020105000420";
const EXPECTED_SIG = "00bed6b1ebc06efac819f5bd57691b18e0f0a4575d0624b27216e6ddfd9168ef9323f6030e705a8fc38b700f0b568f0a064b6cd7d94669007c5f1a224a522662bb4ce338f2b4609dc0454ffddcb2ae137405c9b217db30e2f46183f502872a3dba71d5d7d2035c8f83238e94631edc36b6cbdbf46836f0484bb8d650591934214cd064199b7a274fafba54d37e864fad211d080b9a6703b6a0014853904ccc5b3a13e493084fac7a2f838154830526f42331fcf1e97f255fae108016dd0bff2466c4d97ce634c0f739b4813969ee3d80671910083a98290a9dd78e1fd3294e18151ab24c4c811548f9a65da3a3d1a8e55aa134e4092713fc341e713d1c0f3069";

describe("RSA-SHA256 PKCS#1 v1.5 vs Python cryptography (real 2048-bit key)", fn() {
    test("our modexp + pkcs1_pad reproduce the library's signature byte-for-byte", fn() {
        let digest = Crypto.sha256("<doc>sign me</doc>");
        let digest_info = SHA256_DIGESTINFO + digest;
        let em = Crypto.pkcs1_pad(digest_info, 256);     # 2048-bit key = 256 octets
        let signature = Crypto.modexp(em, D, N);
        assert_eq(signature, EXPECTED_SIG);
    });

    test("verifying the library's signature recovers our DigestInfo", fn() {
        let digest = Crypto.sha256("<doc>sign me</doc>");
        let recovered = Crypto.pkcs1_unpad(Crypto.modexp(EXPECTED_SIG, E, N));
        assert_eq(recovered, SHA256_DIGESTINFO + digest);
    });
});
