//! Portable DDL for **column tables**.
//!
//! The document path needs no schema — a collection is `_key` + `doc`, created
//! on first write. Column-aware models are the opposite: they map to real
//! columns, and someone has to create them. This module is that someone, for
//! migrations that declare a schema Soli itself will own.
//!
//! One migration should run on Postgres, MySQL, and SQLite, so the DSL speaks in
//! Soli types (`string`, `datetime`, `json`, `pk`) and each dialect renders its
//! own SQL. The rendered type names are chosen so that
//! [`super::introspect`] reads the table back as the same Soli types — a table
//! created here is guaranteed to be one column mode can map.
//!
//! Identifiers always go through [`Dialect::quote_ident`], which accepts only
//! `[A-Za-z0-9_]`, and literals are rendered per dialect. A migration is
//! developer-authored, but a stray table name still cannot become SQL.

use super::sql_compile::Dialect;

/// A column type in the portable vocabulary.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DdlType {
    /// Database-generated integer primary key.
    Pk,
    /// UUID primary key — supplied by the app, not generated by the database.
    UuidPk,
    /// Variable-length text with a limit (`VARCHAR`).
    String(u32),
    /// Unbounded text.
    Text,
    Integer,
    BigInt,
    Float,
    /// Exact numeric with precision and scale.
    Decimal(u32, u32),
    Boolean,
    Date,
    DateTime,
    Json,
    Uuid,
    Binary,
}

impl DdlType {
    /// Parse a shorthand type name: `"string"`, `"string(64)"`, `"decimal(10,2)"`.
    pub fn parse(raw: &str) -> Result<Self, String> {
        let lower = raw.trim().to_ascii_lowercase();
        let (base, args) = match lower.split_once('(') {
            Some((base, rest)) => {
                let inner = rest.strip_suffix(')').ok_or_else(|| {
                    format!("column type {raw:?} is missing its closing parenthesis")
                })?;
                (base.trim().to_string(), Some(inner.to_string()))
            }
            None => (lower.clone(), None),
        };

        let parse_args = |count: usize| -> Result<Vec<u32>, String> {
            let raw_args = args.clone().unwrap_or_default();
            let parts: Vec<&str> = raw_args.split(',').map(str::trim).collect();
            if parts.len() != count || parts.iter().any(|p| p.is_empty()) {
                return Err(format!(
                    "column type {raw:?} expects {count} numeric argument(s)"
                ));
            }
            parts
                .iter()
                .map(|p| {
                    p.parse::<u32>().map_err(|_| {
                        format!("column type {raw:?} has a non-numeric argument {p:?}")
                    })
                })
                .collect()
        };

        match base.as_str() {
            "pk" | "primary_key" | "id" => Ok(DdlType::Pk),
            "uuid_pk" => Ok(DdlType::UuidPk),
            "string" | "varchar" => match args {
                None => Ok(DdlType::String(255)),
                Some(_) => Ok(DdlType::String(parse_args(1)?[0])),
            },
            "text" => Ok(DdlType::Text),
            "integer" | "int" => Ok(DdlType::Integer),
            "bigint" | "long" => Ok(DdlType::BigInt),
            "float" | "double" | "real" => Ok(DdlType::Float),
            "decimal" | "numeric" => match args {
                // An unqualified decimal still needs a scale, or the database
                // picks one for you (and Postgres picks "unlimited").
                None => Ok(DdlType::Decimal(10, 2)),
                Some(_) => {
                    let a = parse_args(2)?;
                    Ok(DdlType::Decimal(a[0], a[1]))
                }
            },
            "boolean" | "bool" => Ok(DdlType::Boolean),
            "date" => Ok(DdlType::Date),
            "datetime" | "timestamp" => Ok(DdlType::DateTime),
            "json" | "jsonb" => Ok(DdlType::Json),
            "uuid" => Ok(DdlType::Uuid),
            "binary" | "blob" | "bytea" => Ok(DdlType::Binary),
            other => Err(format!(
                "unknown column type {other:?}. Use one of: pk, uuid_pk, string, \
                 string(n), text, integer, bigint, float, decimal(p,s), boolean, \
                 date, datetime, json, uuid, binary"
            )),
        }
    }

    /// True when the type carries its own `PRIMARY KEY`.
    pub fn is_primary_key(self) -> bool {
        matches!(self, DdlType::Pk | DdlType::UuidPk)
    }

    /// The dialect's SQL for this type.
    ///
    /// The names are picked so introspection maps the column back to the same
    /// Soli type. On SQLite that matters twice over: it has no real types, so
    /// `DATETIME` / `JSON` / `BOOLEAN` / `DECIMAL` exist purely as the declared
    /// names [`super::sqlite::sqlite_coltype`] reads, and `INTEGER PRIMARY KEY`
    /// is what makes a key database-generated.
    pub fn sql(self, d: Dialect) -> String {
        match (self, d) {
            (DdlType::Pk, Dialect::Postgres) => "BIGSERIAL PRIMARY KEY".into(),
            (DdlType::Pk, Dialect::Mysql) => "BIGINT AUTO_INCREMENT PRIMARY KEY".into(),
            (DdlType::Pk, Dialect::Sqlite) => "INTEGER PRIMARY KEY AUTOINCREMENT".into(),

            (DdlType::UuidPk, Dialect::Postgres) => "UUID PRIMARY KEY".into(),
            (DdlType::UuidPk, Dialect::Mysql) => "CHAR(36) PRIMARY KEY".into(),
            (DdlType::UuidPk, Dialect::Sqlite) => "UUID PRIMARY KEY".into(),

            (DdlType::String(n), _) => format!("VARCHAR({n})"),
            (DdlType::Text, _) => "TEXT".into(),

            (DdlType::Integer, Dialect::Mysql) => "INT".into(),
            (DdlType::Integer, _) => "INTEGER".into(),
            (DdlType::BigInt, _) => "BIGINT".into(),

            (DdlType::Float, Dialect::Postgres) => "DOUBLE PRECISION".into(),
            (DdlType::Float, Dialect::Mysql) => "DOUBLE".into(),
            (DdlType::Float, Dialect::Sqlite) => "REAL".into(),

            (DdlType::Decimal(p, s), Dialect::Postgres) => format!("NUMERIC({p},{s})"),
            (DdlType::Decimal(p, s), _) => format!("DECIMAL({p},{s})"),

            (DdlType::Boolean, Dialect::Postgres) => "BOOLEAN".into(),
            // MySQL has no bool; tinyint(1) is the convention introspection reads.
            (DdlType::Boolean, Dialect::Mysql) => "TINYINT(1)".into(),
            (DdlType::Boolean, Dialect::Sqlite) => "BOOLEAN".into(),

            (DdlType::Date, _) => "DATE".into(),

            // Only Postgres stores an offset; the others are documented as UTC.
            (DdlType::DateTime, Dialect::Postgres) => "TIMESTAMPTZ".into(),
            (DdlType::DateTime, _) => "DATETIME".into(),

            (DdlType::Json, Dialect::Postgres) => "JSONB".into(),
            (DdlType::Json, _) => "JSON".into(),

            (DdlType::Uuid, Dialect::Mysql) => "CHAR(36)".into(),
            (DdlType::Uuid, _) => "UUID".into(),

            (DdlType::Binary, Dialect::Postgres) => "BYTEA".into(),
            (DdlType::Binary, _) => "BLOB".into(),
        }
    }
}

/// One column of a table being created or altered.
#[derive(Clone, Debug)]
pub struct ColumnSpec {
    pub name: String,
    pub ty: DdlType,
    pub nullable: bool,
    pub default: Option<serde_json::Value>,
    pub unique: bool,
    /// `PRIMARY KEY` on a type that does not already imply it.
    pub primary_key: bool,
    /// `"users"` or `"users(uuid)"` — a foreign key to that table's column
    /// (`id` when unqualified).
    pub references: Option<String>,
}

impl ColumnSpec {
    fn new(name: String, ty: DdlType) -> Self {
        Self {
            name,
            // A primary key is never nullable; everything else is, unless the
            // migration says otherwise.
            nullable: !ty.is_primary_key(),
            ty,
            default: None,
            unique: false,
            primary_key: false,
            references: None,
        }
    }

    fn is_key(&self) -> bool {
        self.primary_key || self.ty.is_primary_key()
    }
}

/// A table to create.
#[derive(Clone, Debug)]
pub struct TableSpec {
    pub table: String,
    pub columns: Vec<ColumnSpec>,
    /// Append `created_at` / `updated_at`, which the model layer then stamps.
    pub timestamps: bool,
}

/// Parse the migration DSL's column hash into a [`TableSpec`].
///
/// Pairs arrive in declaration order (Soli hashes are ordered), so the created
/// table's columns are in the order they were written.
pub fn parse_table_spec(
    table: &str,
    pairs: &[(String, serde_json::Value)],
) -> Result<TableSpec, String> {
    let mut spec = TableSpec {
        table: table.to_string(),
        columns: Vec::new(),
        timestamps: false,
    };

    for (key, value) in pairs {
        // `timestamps: true` is a directive, not a column.
        if key == "timestamps" {
            spec.timestamps = value
                .as_bool()
                .ok_or_else(|| format!("\"timestamps\" expects true or false, got {value}"))?;
            continue;
        }
        spec.columns.push(parse_column(key, value)?);
    }

    if spec.columns.is_empty() {
        return Err(format!(
            "create_table({table:?}, …) needs at least one column. Call \
             create_table({table:?}) with no column hash for a document table."
        ));
    }

    // A composite key would produce a table column-aware models cannot map, so
    // refuse it here rather than at the first query.
    let keys: Vec<&str> = spec
        .columns
        .iter()
        .filter(|c| c.is_key())
        .map(|c| c.name.as_str())
        .collect();
    if keys.len() > 1 {
        return Err(format!(
            "table {table:?} declares {} primary keys ({}). Column-aware models \
             support a single-column primary key.",
            keys.len(),
            keys.join(", ")
        ));
    }

    Ok(spec)
}

/// Parse one column: a shorthand type string, or a hash with options.
pub fn parse_column(name: &str, value: &serde_json::Value) -> Result<ColumnSpec, String> {
    match value {
        serde_json::Value::String(ty) => Ok(ColumnSpec::new(name.to_string(), DdlType::parse(ty)?)),
        serde_json::Value::Object(map) => {
            let raw_ty = map
                .get("type")
                .and_then(|v| v.as_str())
                .ok_or_else(|| format!("column {name:?} needs a \"type\""))?;
            let mut col = ColumnSpec::new(name.to_string(), DdlType::parse(raw_ty)?);
            if let Some(limit) = map.get("limit") {
                let n = limit
                    .as_u64()
                    .ok_or_else(|| format!("column {name:?}: \"limit\" expects a number"))?;
                match col.ty {
                    DdlType::String(_) => col.ty = DdlType::String(n as u32),
                    _ => {
                        return Err(format!(
                            "column {name:?}: \"limit\" only applies to a string column"
                        ))
                    }
                }
            }
            if let Some(nullable) = map.get("null") {
                col.nullable = nullable
                    .as_bool()
                    .ok_or_else(|| format!("column {name:?}: \"null\" expects true or false"))?;
            }
            if let Some(unique) = map.get("unique") {
                col.unique = unique
                    .as_bool()
                    .ok_or_else(|| format!("column {name:?}: \"unique\" expects true or false"))?;
            }
            if let Some(pk) = map.get("primary_key") {
                col.primary_key = pk.as_bool().ok_or_else(|| {
                    format!("column {name:?}: \"primary_key\" expects true or false")
                })?;
                if col.primary_key {
                    col.nullable = false;
                }
            }
            if let Some(default) = map.get("default") {
                col.default = Some(default.clone());
            }
            if let Some(references) = map.get("references") {
                col.references = Some(
                    references
                        .as_str()
                        .ok_or_else(|| {
                            format!("column {name:?}: \"references\" expects a table name")
                        })?
                        .to_string(),
                );
            }
            // A misspelled option would otherwise be ignored, and the column
            // would quietly not have the property the migration asked for.
            if let Some(unknown) = map.keys().find(|k| {
                !matches!(
                    k.as_str(),
                    "type" | "limit" | "null" | "unique" | "primary_key" | "default" | "references"
                )
            }) {
                return Err(format!(
                    "column {name:?}: unknown option {unknown:?}. Known: type, limit, \
                     null, unique, primary_key, default, references"
                ));
            }
            Ok(col)
        }
        other => Err(format!(
            "column {name:?} expects a type string or an options hash, got {other}"
        )),
    }
}

/// Tables the engine owns. A migration must not create, drop, or rename them —
/// wiping `_migrations` would re-run every file, and `_jobs` / `_cron_jobs`
/// are the job engine's store. SQLite's catalog names are listed too so a
/// `drop_table` cannot point at them.
pub fn is_reserved_table(name: &str) -> bool {
    matches!(
        name.to_ascii_lowercase().as_str(),
        "_migrations"
            | "_jobs"
            | "_cron_jobs"
            | "sqlite_master"
            | "sqlite_temp_master"
            | "sqlite_sequence"
    )
}

/// Refuse a table name the engine owns. Called from every user-facing DDL
/// helper; internal `ensure_table("_jobs")` does not go through here.
pub fn assert_user_table(name: &str) -> Result<(), String> {
    if is_reserved_table(name) {
        return Err(format!(
            "{name:?} is reserved by Soli (_migrations, _jobs, _cron_jobs). \
             Pick another table name."
        ));
    }
    Ok(())
}

/// Render a string as a SQL literal for `DEFAULT`.
///
/// Quote-doubling is enough on Postgres and SQLite. MySQL treats `\` as an
/// escape unless `NO_BACKSLASH_ESCAPES` is on, so `'x\', extra INT --'` would
/// close the string early and become a second column. Backslash, quote, NUL,
/// newline, CR, and SUB are escaped the way `mysql_real_escape_string` does.
fn escape_sql_string(d: Dialect, s: &str) -> String {
    match d {
        Dialect::Mysql => {
            let mut out = String::with_capacity(s.len() + 2);
            out.push('\'');
            for c in s.chars() {
                match c {
                    '\0' => out.push_str("\\0"),
                    '\n' => out.push_str("\\n"),
                    '\r' => out.push_str("\\r"),
                    '\\' => out.push_str("\\\\"),
                    '\'' => out.push_str("\\'"),
                    '\u{001a}' => out.push_str("\\Z"),
                    other => out.push(other),
                }
            }
            out.push('\'');
            out
        }
        Dialect::Postgres | Dialect::Sqlite => format!("'{}'", s.replace('\'', "''")),
    }
}

/// Render a default value as a SQL literal.
fn default_literal(d: Dialect, col: &ColumnSpec) -> Result<String, String> {
    let Some(value) = &col.default else {
        return Ok(String::new());
    };
    let literal = match value {
        serde_json::Value::Null => "NULL".to_string(),
        serde_json::Value::Bool(b) => match d {
            Dialect::Postgres => if *b { "TRUE" } else { "FALSE" }.to_string(),
            // No boolean type on either: 0/1 is what the column holds.
            _ => i64::from(*b).to_string(),
        },
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => escape_sql_string(d, s),
        // A JSON/array default differs per dialect (and MySQL needs an
        // expression default), so say so rather than emit something that only
        // works on one backend.
        serde_json::Value::Array(_) | serde_json::Value::Object(_) => {
            return Err(format!(
                "column {:?}: a hash or array default is not portable. Set the \
                 value in the model instead (a `before_save` callback, or the \
                 create call).",
                col.name
            ))
        }
    };
    Ok(format!(" DEFAULT {literal}"))
}

/// `"users"` / `"users(uuid)"` → a quoted `REFERENCES` target.
fn references_target(d: Dialect, raw: &str) -> Result<String, String> {
    let (table, column) = match raw.split_once('(') {
        Some((table, rest)) => {
            let col = rest
                .strip_suffix(')')
                .ok_or_else(|| format!("references {raw:?} is missing its closing parenthesis"))?;
            (table.trim(), col.trim())
        }
        None => (raw.trim(), "id"),
    };
    Ok(format!(
        "{}({})",
        d.quote_ident(table)?,
        d.quote_ident(column)?
    ))
}

/// One column's definition inside `CREATE TABLE` / `ADD COLUMN`.
///
/// `inline_fk` is false on MySQL, where an inline `REFERENCES` clause is parsed
/// and **silently ignored** — the constraint has to be declared at table level.
fn column_fragment(d: Dialect, col: &ColumnSpec, inline_fk: bool) -> Result<String, String> {
    let mut out = format!("{} {}", d.quote_ident(&col.name)?, col.ty.sql(d));
    // A key is NOT NULL by definition; saying it twice is noise (and on SQLite,
    // `INTEGER PRIMARY KEY NOT NULL` is a different rowid story).
    if col.primary_key && !col.ty.is_primary_key() {
        out.push_str(" PRIMARY KEY");
    } else if !col.nullable && !col.is_key() {
        out.push_str(" NOT NULL");
    }
    if col.unique && !col.is_key() {
        out.push_str(" UNIQUE");
    }
    out.push_str(&default_literal(d, col)?);
    if inline_fk {
        if let Some(references) = &col.references {
            out.push_str(&format!(
                " REFERENCES {}",
                references_target(d, references)?
            ));
        }
    }
    Ok(out)
}

/// The two timestamp columns, stamped by the model layer and defaulted by the
/// database so a write from outside Soli still fills them.
fn timestamp_columns() -> Vec<ColumnSpec> {
    ["created_at", "updated_at"]
        .iter()
        .map(|name| ColumnSpec {
            nullable: false,
            ..ColumnSpec::new((*name).to_string(), DdlType::DateTime)
        })
        .collect()
}

/// `CREATE TABLE IF NOT EXISTS` for a column table.
pub fn create_table_sql(d: Dialect, spec: &TableSpec) -> Result<String, String> {
    assert_user_table(&spec.table)?;
    let table = d.quote_ident(&spec.table)?;
    let mut parts = Vec::with_capacity(spec.columns.len() + 2);
    let inline_fk = d != Dialect::Mysql;

    for col in &spec.columns {
        parts.push(column_fragment(d, col, inline_fk)?);
    }
    if spec.timestamps {
        for col in timestamp_columns() {
            let mut fragment = column_fragment(d, &col, inline_fk)?;
            fragment.push_str(" DEFAULT CURRENT_TIMESTAMP");
            parts.push(fragment);
        }
    }
    // MySQL needs foreign keys as table-level constraints.
    if !inline_fk {
        for col in &spec.columns {
            if let Some(references) = &col.references {
                parts.push(format!(
                    "FOREIGN KEY ({}) REFERENCES {}",
                    d.quote_ident(&col.name)?,
                    references_target(d, references)?
                ));
            }
        }
    }

    Ok(format!(
        "CREATE TABLE IF NOT EXISTS {table} (\n\t{}\n)",
        parts.join(",\n\t")
    ))
}

/// `DROP TABLE IF EXISTS`.
pub fn drop_table_sql(d: Dialect, table: &str) -> Result<String, String> {
    assert_user_table(table)?;
    Ok(format!("DROP TABLE IF EXISTS {}", d.quote_ident(table)?))
}

/// `ALTER TABLE … ADD COLUMN`.
pub fn add_column_sql(d: Dialect, table: &str, col: &ColumnSpec) -> Result<String, String> {
    assert_user_table(table)?;
    // SQLite's ALTER TABLE is narrow, and the failures are confusing after the
    // fact — name them now, with the way around each.
    if d == Dialect::Sqlite {
        if col.unique || col.is_key() {
            return Err(format!(
                "SQLite cannot add a UNIQUE or PRIMARY KEY column to an existing \
                 table. Add {:?} plain, then call add_index({table:?}, [{:?}], \
                 {{ \"unique\": true }}).",
                col.name, col.name
            ));
        }
        if !col.nullable && col.default.is_none() {
            return Err(format!(
                "SQLite cannot add the NOT NULL column {:?} without a default \
                 (existing rows would have no value). Give it a \"default\", or \
                 add it nullable.",
                col.name
            ));
        }
    }
    Ok(format!(
        "ALTER TABLE {} ADD COLUMN {}",
        d.quote_ident(table)?,
        column_fragment(d, col, d != Dialect::Mysql)?
    ))
}

/// `ALTER TABLE … DROP COLUMN`.
pub fn drop_column_sql(d: Dialect, table: &str, column: &str) -> Result<String, String> {
    assert_user_table(table)?;
    Ok(format!(
        "ALTER TABLE {} DROP COLUMN {}",
        d.quote_ident(table)?,
        d.quote_ident(column)?
    ))
}

/// `ALTER TABLE … RENAME COLUMN … TO …` (MySQL 8+).
pub fn rename_column_sql(d: Dialect, table: &str, from: &str, to: &str) -> Result<String, String> {
    assert_user_table(table)?;
    Ok(format!(
        "ALTER TABLE {} RENAME COLUMN {} TO {}",
        d.quote_ident(table)?,
        d.quote_ident(from)?,
        d.quote_ident(to)?
    ))
}

/// `ALTER TABLE … RENAME TO …`.
pub fn rename_table_sql(d: Dialect, from: &str, to: &str) -> Result<String, String> {
    assert_user_table(from)?;
    assert_user_table(to)?;
    Ok(format!(
        "ALTER TABLE {} RENAME TO {}",
        d.quote_ident(from)?,
        d.quote_ident(to)?
    ))
}

/// Default index name for `table` over `columns`.
pub fn index_name(table: &str, columns: &[String]) -> String {
    format!("idx_{}_{}", table, columns.join("_"))
}

/// `CREATE [UNIQUE] INDEX`.
pub fn add_index_sql(
    d: Dialect,
    table: &str,
    columns: &[String],
    name: Option<&str>,
    unique: bool,
) -> Result<String, String> {
    assert_user_table(table)?;
    if columns.is_empty() {
        return Err(format!("add_index({table:?}, …) needs at least one column"));
    }
    let owned = index_name(table, columns);
    let index = d.quote_ident(name.unwrap_or(&owned))?;
    let cols = columns
        .iter()
        .map(|c| d.quote_ident(c))
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");
    let unique_sql = if unique { "UNIQUE " } else { "" };
    // MySQL has no IF NOT EXISTS for CREATE INDEX.
    let guard = if d == Dialect::Mysql {
        ""
    } else {
        "IF NOT EXISTS "
    };
    Ok(format!(
        "CREATE {unique_sql}INDEX {guard}{index} ON {} ({cols})",
        d.quote_ident(table)?
    ))
}

/// `DROP INDEX` — MySQL needs the table, the others do not.
pub fn drop_index_sql(d: Dialect, table: &str, name: &str) -> Result<String, String> {
    assert_user_table(table)?;
    let index = d.quote_ident(name)?;
    Ok(match d {
        Dialect::Mysql => format!("DROP INDEX {index} ON {}", d.quote_ident(table)?),
        _ => format!("DROP INDEX IF EXISTS {index}"),
    })
}

/// A JSON-field index on a **document table** (`_key` + `doc`).
///
/// Document tables carry no indexes beyond the primary key, so every hash
/// filter is a sequential scan plus a per-row JSON extract. This builds an index
/// on the extract itself.
///
/// The expression must be **identical** to the one the query emits
/// ([`Dialect::json_text`], which `compile_where` uses for string equality) or
/// the planner will not use it. MySQL is the exception: it cannot index a JSON
/// extract directly, so a generated `STORED` column carries the value and the
/// index sits on that — hence a `Vec` of statements rather than one.
pub fn doc_index_sql(
    d: Dialect,
    table: &str,
    fields: &[String],
    name: &str,
    unique: bool,
) -> Result<Vec<String>, String> {
    if fields.is_empty() {
        return Err(format!("index {name:?} on {table:?} names no fields"));
    }
    for field in fields {
        // Field names reach SQL inside a quoted JSON path, so they get the same
        // identifier rules rather than a looser check.
        d.quote_ident(field)?;
    }
    let table_q = d.quote_ident(table)?;
    let index_q = d.quote_ident(name)?;
    let unique_sql = if unique { "UNIQUE " } else { "" };

    match d {
        Dialect::Postgres | Dialect::Sqlite => {
            let exprs = fields
                .iter()
                .map(|f| d.json_text(f))
                .collect::<Vec<_>>()
                .join(", ");
            Ok(vec![format!(
                "CREATE {unique_sql}INDEX IF NOT EXISTS {index_q} ON {table_q} ({exprs})"
            )])
        }
        Dialect::Mysql => {
            let mut statements = Vec::with_capacity(fields.len() + 1);
            let mut columns = Vec::with_capacity(fields.len());
            for field in fields {
                let generated = generated_column_name(field);
                let column_q = d.quote_ident(&generated)?;
                // 191 chars keeps the index inside InnoDB's key limit on
                // utf8mb4; longer values still store fine in `doc`.
                statements.push(format!(
                    "ALTER TABLE {table_q} ADD COLUMN {column_q} VARCHAR(191) \
                     AS (JSON_UNQUOTE(JSON_EXTRACT(doc, '$.{field}'))) STORED"
                ));
                columns.push(column_q);
            }
            // No IF NOT EXISTS for CREATE INDEX on MySQL: the caller checks
            // first (see `sql::ensure_doc_index`).
            statements.push(format!(
                "CREATE {unique_sql}INDEX {index_q} ON {table_q} ({})",
                columns.join(", ")
            ));
            Ok(statements)
        }
    }
}

/// Name of the generated column MySQL indexes for `field`.
pub fn generated_column_name(field: &str) -> String {
    format!("_idx_{field}")
}

/// Default name for a document-field index.
pub fn doc_index_name(table: &str, fields: &[String]) -> String {
    format!("idx_{}_{}", table, fields.join("_"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Ordered pairs, the way the migration DSL delivers them: Soli hashes are
    /// insertion-ordered, so a `serde_json` object (which sorts its keys) would
    /// not model the input faithfully.
    fn pairs(raw: Vec<(&str, serde_json::Value)>) -> Vec<(String, serde_json::Value)> {
        raw.into_iter().map(|(k, v)| (k.to_string(), v)).collect()
    }

    fn orders_spec() -> TableSpec {
        parse_table_spec(
            "orders",
            &pairs(vec![
                ("id", serde_json::json!("pk")),
                (
                    "code",
                    serde_json::json!({ "type": "string", "limit": 64, "null": false, "unique": true }),
                ),
                ("amount", serde_json::json!("decimal(10,2)")),
                ("paid", serde_json::json!({ "type": "boolean", "default": false })),
                ("meta", serde_json::json!("json")),
                ("user_id", serde_json::json!({ "type": "bigint", "references": "users" })),
                ("timestamps", serde_json::json!(true)),
            ]),
        )
        .expect("spec")
    }

    #[test]
    fn shorthand_types_parse() {
        assert_eq!(DdlType::parse("pk").unwrap(), DdlType::Pk);
        assert_eq!(DdlType::parse("string").unwrap(), DdlType::String(255));
        assert_eq!(DdlType::parse("string(64)").unwrap(), DdlType::String(64));
        assert_eq!(DdlType::parse("STRING(10)").unwrap(), DdlType::String(10));
        assert_eq!(
            DdlType::parse("decimal(12,4)").unwrap(),
            DdlType::Decimal(12, 4)
        );
        assert_eq!(DdlType::parse("decimal").unwrap(), DdlType::Decimal(10, 2));
        assert_eq!(DdlType::parse("timestamp").unwrap(), DdlType::DateTime);
        assert_eq!(DdlType::parse("bool").unwrap(), DdlType::Boolean);
        // An unknown type lists the vocabulary rather than guessing.
        let err = DdlType::parse("money").unwrap_err();
        assert!(
            err.contains("money") && err.contains("decimal(p,s)"),
            "{err}"
        );
        assert!(DdlType::parse("string(abc)").is_err());
        assert!(DdlType::parse("decimal(10)").is_err());
    }

    #[test]
    fn column_order_follows_declaration_order() {
        let spec = orders_spec();
        let names: Vec<&str> = spec.columns.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(
            names,
            ["id", "code", "amount", "paid", "meta", "user_id"],
            "columns must be created in the order they were written"
        );
        assert!(
            spec.timestamps,
            "\"timestamps\" is a directive, not a column"
        );
    }

    #[test]
    fn postgres_create_table() {
        let sql = create_table_sql(Dialect::Postgres, &orders_spec()).unwrap();
        assert!(
            sql.starts_with("CREATE TABLE IF NOT EXISTS \"orders\" ("),
            "{sql}"
        );
        assert!(sql.contains("\"id\" BIGSERIAL PRIMARY KEY"), "{sql}");
        assert!(
            sql.contains("\"code\" VARCHAR(64) NOT NULL UNIQUE"),
            "{sql}"
        );
        assert!(sql.contains("\"amount\" NUMERIC(10,2)"), "{sql}");
        assert!(sql.contains("\"paid\" BOOLEAN DEFAULT FALSE"), "{sql}");
        assert!(sql.contains("\"meta\" JSONB"), "{sql}");
        // Postgres takes the foreign key inline.
        assert!(
            sql.contains("\"user_id\" BIGINT REFERENCES \"users\"(\"id\")"),
            "{sql}"
        );
        assert!(
            sql.contains("\"created_at\" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP"),
            "{sql}"
        );
    }

    #[test]
    fn mysql_create_table_lifts_foreign_keys_to_table_level() {
        let sql = create_table_sql(Dialect::Mysql, &orders_spec()).unwrap();
        assert!(
            sql.contains("`id` BIGINT AUTO_INCREMENT PRIMARY KEY"),
            "{sql}"
        );
        assert!(sql.contains("`paid` TINYINT(1) DEFAULT 0"), "{sql}");
        assert!(sql.contains("`meta` JSON"), "{sql}");
        assert!(sql.contains("`created_at` DATETIME"), "{sql}");
        // An inline REFERENCES is silently ignored by MySQL, so the constraint
        // must be declared at table level or the foreign key would not exist.
        assert!(
            !sql.contains("`user_id` BIGINT REFERENCES"),
            "inline FK on MySQL is a no-op: {sql}"
        );
        assert!(
            sql.contains("FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)"),
            "{sql}"
        );
    }

    #[test]
    fn sqlite_create_table_uses_names_introspection_reads_back() {
        let sql = create_table_sql(Dialect::Sqlite, &orders_spec()).unwrap();
        // INTEGER PRIMARY KEY aliases the rowid, which is what makes the key
        // database-generated for column mode.
        assert!(
            sql.contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"),
            "{sql}"
        );
        assert!(sql.contains("\"amount\" DECIMAL(10,2)"), "{sql}");
        assert!(sql.contains("\"paid\" BOOLEAN DEFAULT 0"), "{sql}");
        assert!(sql.contains("\"meta\" JSON"), "{sql}");
        assert!(sql.contains("\"created_at\" DATETIME"), "{sql}");

        // Every declared type must map back to the Soli type it came from.
        use crate::db::introspect::ColType;
        use crate::db::sqlite::sqlite_coltype;
        assert_eq!(sqlite_coltype("DECIMAL(10,2)"), ColType::Decimal);
        assert_eq!(sqlite_coltype("BOOLEAN"), ColType::Bool);
        assert_eq!(sqlite_coltype("JSON"), ColType::Json);
        assert_eq!(sqlite_coltype("DATETIME"), ColType::DateTime);
        assert_eq!(sqlite_coltype("INTEGER"), ColType::Int);
        assert_eq!(sqlite_coltype("VARCHAR(64)"), ColType::Text);
    }

    #[test]
    fn composite_and_empty_keys_are_refused() {
        let err = parse_table_spec(
            "memberships",
            &pairs(vec![
                (
                    "user_id",
                    serde_json::json!({ "type": "bigint", "primary_key": true }),
                ),
                (
                    "group_id",
                    serde_json::json!({ "type": "bigint", "primary_key": true }),
                ),
            ]),
        )
        .unwrap_err();
        assert!(
            err.contains("primary key") || err.contains("primary keys"),
            "{err}"
        );

        // A table with no columns is the document-table call, spelled wrong.
        let err = parse_table_spec("posts", &[]).unwrap_err();
        assert!(err.contains("at least one column"), "{err}");
    }

    #[test]
    fn unknown_options_and_bad_values_are_named() {
        let err = parse_column(
            "code",
            &serde_json::json!({ "type": "string", "nulll": true }),
        )
        .unwrap_err();
        assert!(err.contains("nulll"), "{err}");
        let err = parse_column("code", &serde_json::json!({ "limit": 10 })).unwrap_err();
        assert!(err.contains("needs a \"type\""), "{err}");
        let err =
            parse_column("qty", &serde_json::json!({ "type": "integer", "limit": 5 })).unwrap_err();
        assert!(err.contains("string column"), "{err}");
        // A non-portable default is refused rather than rendered for one dialect.
        let col = parse_column(
            "meta",
            &serde_json::json!({ "type": "json", "default": {} }),
        )
        .unwrap();
        let err = default_literal(Dialect::Postgres, &col).unwrap_err();
        assert!(err.contains("not portable"), "{err}");
    }

    #[test]
    fn alter_statements_per_dialect() {
        let col = parse_column("note", &serde_json::json!({ "type": "text" })).unwrap();
        assert_eq!(
            add_column_sql(Dialect::Postgres, "orders", &col).unwrap(),
            "ALTER TABLE \"orders\" ADD COLUMN \"note\" TEXT"
        );
        assert_eq!(
            add_column_sql(Dialect::Mysql, "orders", &col).unwrap(),
            "ALTER TABLE `orders` ADD COLUMN `note` TEXT"
        );
        assert_eq!(
            drop_column_sql(Dialect::Sqlite, "orders", "note").unwrap(),
            "ALTER TABLE \"orders\" DROP COLUMN \"note\""
        );
        assert_eq!(
            rename_column_sql(Dialect::Postgres, "orders", "note", "memo").unwrap(),
            "ALTER TABLE \"orders\" RENAME COLUMN \"note\" TO \"memo\""
        );
        assert_eq!(
            rename_table_sql(Dialect::Mysql, "orders", "sales").unwrap(),
            "ALTER TABLE `orders` RENAME TO `sales`"
        );
    }

    #[test]
    fn sqlite_alter_limits_are_explained_not_hit_at_runtime() {
        let unique = parse_column(
            "code",
            &serde_json::json!({ "type": "string", "unique": true }),
        )
        .unwrap();
        let err = add_column_sql(Dialect::Sqlite, "orders", &unique).unwrap_err();
        assert!(err.contains("add_index"), "{err}");
        // The same column is fine on Postgres.
        assert!(add_column_sql(Dialect::Postgres, "orders", &unique).is_ok());

        let not_null = parse_column(
            "code",
            &serde_json::json!({ "type": "string", "null": false }),
        )
        .unwrap();
        let err = add_column_sql(Dialect::Sqlite, "orders", &not_null).unwrap_err();
        assert!(err.contains("default"), "{err}");
        // With a default it is accepted.
        let with_default = parse_column(
            "code",
            &serde_json::json!({ "type": "string", "null": false, "default": "n/a" }),
        )
        .unwrap();
        let sql = add_column_sql(Dialect::Sqlite, "orders", &with_default).unwrap();
        assert!(sql.contains("NOT NULL DEFAULT 'n/a'"), "{sql}");
    }

    #[test]
    fn index_statements() {
        let cols = vec!["code".to_string()];
        assert_eq!(
            add_index_sql(Dialect::Postgres, "orders", &cols, None, true).unwrap(),
            "CREATE UNIQUE INDEX IF NOT EXISTS \"idx_orders_code\" ON \"orders\" (\"code\")"
        );
        // MySQL has no IF NOT EXISTS for CREATE INDEX.
        assert_eq!(
            add_index_sql(Dialect::Mysql, "orders", &cols, None, false).unwrap(),
            "CREATE INDEX `idx_orders_code` ON `orders` (`code`)"
        );
        // …and it needs the table on DROP INDEX, unlike the other two.
        assert_eq!(
            drop_index_sql(Dialect::Mysql, "orders", "idx_orders_code").unwrap(),
            "DROP INDEX `idx_orders_code` ON `orders`"
        );
        assert_eq!(
            drop_index_sql(Dialect::Sqlite, "orders", "idx_orders_code").unwrap(),
            "DROP INDEX IF EXISTS \"idx_orders_code\""
        );
        assert!(add_index_sql(Dialect::Postgres, "orders", &[], None, false).is_err());
    }

    #[test]
    fn document_field_indexes_match_the_query_expression() {
        let fields = vec!["status".to_string()];

        // The index expression must be byte-identical to what `compile_where`
        // emits for a string filter, or the planner ignores the index.
        let pg = doc_index_sql(
            Dialect::Postgres,
            "posts",
            &fields,
            "idx_posts_status",
            false,
        )
        .unwrap();
        assert_eq!(pg.len(), 1);
        assert_eq!(
            pg[0],
            "CREATE INDEX IF NOT EXISTS \"idx_posts_status\" ON \"posts\" ((doc->>'status'))"
        );
        assert!(pg[0].contains(&Dialect::Postgres.json_text("status")));

        let lite =
            doc_index_sql(Dialect::Sqlite, "posts", &fields, "idx_posts_status", true).unwrap();
        assert_eq!(
            lite[0],
            "CREATE UNIQUE INDEX IF NOT EXISTS \"idx_posts_status\" ON \"posts\" ((doc ->> '$.status'))"
        );
        assert!(lite[0].contains(&Dialect::Sqlite.json_text("status")));
    }

    #[test]
    fn mysql_indexes_a_generated_column_because_it_cannot_index_json() {
        let fields = vec!["status".to_string(), "author".to_string()];
        let sql = doc_index_sql(
            Dialect::Mysql,
            "posts",
            &fields,
            "idx_posts_status_author",
            false,
        )
        .unwrap();
        // One generated column per field, then the index over them.
        assert_eq!(sql.len(), 3);
        assert!(
            sql[0].contains("ADD COLUMN `_idx_status` VARCHAR(191)"),
            "{}",
            sql[0]
        );
        assert!(sql[0].contains("STORED"), "{}", sql[0]);
        assert!(sql[1].contains("`_idx_author`"), "{}", sql[1]);
        assert_eq!(
            sql[2],
            "CREATE INDEX `idx_posts_status_author` ON `posts` (`_idx_status`, `_idx_author`)"
        );
        // MySQL has no IF NOT EXISTS here — existence is checked by the caller.
        assert!(!sql[2].contains("IF NOT EXISTS"));
    }

    #[test]
    fn a_document_index_validates_its_names() {
        assert!(doc_index_sql(Dialect::Postgres, "posts", &[], "i", false).is_err());
        // A field name is interpolated into a JSON path, so it takes the same
        // identifier rules rather than a looser check.
        let bad = vec!["status'); DROP TABLE users; --".to_string()];
        assert!(doc_index_sql(Dialect::Postgres, "posts", &bad, "i", false).is_err());
        assert!(doc_index_sql(Dialect::Sqlite, "posts", &bad, "i", false).is_err());
        assert_eq!(
            doc_index_name("posts", &["status".into(), "author".into()]),
            "idx_posts_status_author"
        );
    }

    #[test]
    fn a_quoted_identifier_cannot_smuggle_sql() {
        let spec = TableSpec {
            table: "orders\"; DROP TABLE users; --".into(),
            columns: vec![ColumnSpec::new("id".into(), DdlType::Pk)],
            timestamps: false,
        };
        assert!(create_table_sql(Dialect::Postgres, &spec).is_err());
        let col = ColumnSpec::new("a b".into(), DdlType::Text);
        assert!(add_column_sql(Dialect::Postgres, "orders", &col).is_err());
    }

    #[test]
    fn mysql_string_default_cannot_break_out_of_the_literal() {
        // Classic MySQL breakout: quote-doubling alone turns
        // `x\', extra INT --` into DEFAULT 'x\', extra INT --' which MySQL
        // reads as string `x` plus a second column. Escaping `\` first
        // keeps it one literal.
        let col = parse_column(
            "note",
            &serde_json::json!({ "type": "string", "default": "x', extra INT --" }),
        )
        .unwrap();
        // A backslash before the quote is the actual attack.
        let attack = parse_column(
            "note",
            &serde_json::json!({ "type": "string", "default": "x\\', extra INT --" }),
        )
        .unwrap();

        let mysql = add_column_sql(Dialect::Mysql, "orders", &attack).unwrap();
        assert!(
            mysql.contains(r"DEFAULT 'x\\\', extra INT --'"),
            "backslash and quote must both be escaped: {mysql}"
        );
        assert!(
            !mysql.contains(", extra INT --'") || mysql.contains(r"\', extra INT --'"),
            "the payload must stay inside the literal: {mysql}"
        );

        // Postgres / SQLite: quote-doubling is enough; backslash is ordinary.
        let pg = default_literal(Dialect::Postgres, &col).unwrap();
        assert_eq!(pg, " DEFAULT 'x'', extra INT --'");
        let lite = default_literal(Dialect::Sqlite, &attack).unwrap();
        assert_eq!(lite, " DEFAULT 'x\\'', extra INT --'");

        // The breakout must not become a second column of CREATE TABLE.
        let spec = parse_table_spec(
            "orders",
            &pairs(vec![
                ("id", serde_json::json!("pk")),
                (
                    "note",
                    serde_json::json!({ "type": "string", "default": "x\\', extra INT --" }),
                ),
            ]),
        )
        .unwrap();
        let create = create_table_sql(Dialect::Mysql, &spec).unwrap();
        assert!(
            !create.to_ascii_lowercase().contains("\n\textra "),
            "injected column must not appear: {create}"
        );
    }

    #[test]
    fn reserved_table_names_are_refused() {
        for name in [
            "_migrations",
            "_jobs",
            "_cron_jobs",
            "_JOBS",
            "sqlite_master",
        ] {
            let spec = TableSpec {
                table: name.into(),
                columns: vec![ColumnSpec::new("id".into(), DdlType::Pk)],
                timestamps: false,
            };
            let err = create_table_sql(Dialect::Postgres, &spec).unwrap_err();
            assert!(err.contains("reserved"), "{name}: {err}");
            assert!(drop_table_sql(Dialect::Sqlite, name).is_err());
            assert!(rename_table_sql(Dialect::Mysql, name, "ok").is_err());
            assert!(rename_table_sql(Dialect::Mysql, "ok", name).is_err());
        }
        // A normal table still works.
        assert!(drop_table_sql(Dialect::Postgres, "orders").is_ok());
    }
}
