//! `soli db:schema:dump` / `db:schema:load`.
//!
//! A dump is dialect SQL plus the list of applied migration versions, so a
//! fresh database can be built without replaying every migration file.

/// Header + CREATE statements.
pub fn format_dump(adapter: &str, versions: &[(String, String)], stmts: &[String]) -> String {
    let vers = versions
        .iter()
        .map(|(v, n)| format!("{v}_{n}"))
        .collect::<Vec<_>>()
        .join(",");
    let mut out = String::new();
    out.push_str("-- Soli schema dump. Generated by `soli db:schema:dump`.\n");
    out.push_str("-- Do not edit by hand; regenerate after migrating.\n");
    out.push_str(&format!("-- adapter: {adapter}\n"));
    out.push_str(&format!("-- versions: {vers}\n\n"));
    for stmt in stmts {
        let s = stmt.trim().trim_end_matches(';');
        if !s.is_empty() {
            out.push_str(s);
            out.push_str(";\n\n");
        }
    }
    out
}

/// Applied versions recorded in a dump header (`-- versions: a,b`).
pub fn parse_versions(dump: &str) -> Vec<(String, String)> {
    for line in dump.lines() {
        let line = line.trim();
        let Some(rest) = line
            .strip_prefix("-- versions:")
            .or_else(|| line.strip_prefix("--versions:"))
        else {
            continue;
        };
        return rest
            .split(',')
            .filter_map(|raw| {
                let raw = raw.trim();
                if raw.is_empty() {
                    return None;
                }
                // `20260813000001_create_invoices` → (version, name)
                let (version, name) = raw.split_once('_').unwrap_or((raw, raw));
                Some((version.to_string(), name.to_string()))
            })
            .collect();
    }
    Vec::new()
}

/// The SQL body with header comments stripped.
pub fn sql_body(dump: &str) -> String {
    dump.lines()
        .filter(|line| !line.trim_start().starts_with("--"))
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_then_parse_round_trips_versions_and_body() {
        let dump = format_dump(
            "sqlite",
            &[
                ("20260813000001".into(), "create_invoices".into()),
                ("20260813000002".into(), "add_note".into()),
            ],
            &[
                "CREATE TABLE invoices (id INTEGER PRIMARY KEY)".into(),
                "CREATE INDEX idx_invoices_code ON invoices (code)".into(),
            ],
        );
        assert!(dump.contains("-- adapter: sqlite"));
        assert!(dump.contains("CREATE TABLE invoices"));
        let versions = parse_versions(&dump);
        assert_eq!(
            versions,
            vec![
                ("20260813000001".into(), "create_invoices".into()),
                ("20260813000002".into(), "add_note".into()),
            ]
        );
        let body = sql_body(&dump);
        assert!(body.contains("CREATE TABLE invoices"));
        assert!(!body.contains("-- adapter"));
    }

    #[test]
    fn parse_versions_skips_empty_and_missing_headers() {
        assert!(parse_versions("CREATE TABLE t (id INT);").is_empty());
        assert!(parse_versions("-- versions:   ").is_empty());
    }
}
