//! Templates for `soli generate app_links`.

pub const WELL_KNOWN_CONTROLLER: &str = r#"# Well-known proof files for Universal Links / Android App Links.
# Generated by `soli generate app_links`. Fill ENV values before deploy.

def android(req)
  {
    "headers": { "Content-Type": "application/json" },
    "body": AppLinks.android(
      ENV["ANDROID_PACKAGE"] || "{{ANDROID_PACKAGE}}",
      [ENV["ANDROID_CERT_SHA256"] || "{{ANDROID_SHA256}}"]
    )
  }
end

def apple(req)
  {
    "headers": { "Content-Type": "application/json" },
    "body": AppLinks.apple(
      ENV["APPLE_APP_ID"] || "{{APPLE_APP_ID}}",
      {{APPLE_PATHS}}
    )
  }
end
"#;

pub const ROUTES_MARKER: &str = "# --- soli generate app_links ---";

pub fn routes_snippet() -> String {
    format!(
        r#"
{marker}
get("/.well-known/assetlinks.json", "well_known#android");
get("/.well-known/apple-app-site-association", "well_known#apple");
# --- end soli generate app_links ---
"#,
        marker = ROUTES_MARKER
    )
}
