//! Template strings for `soli generate auth`.
//!
//! Static files are embedded with `include_str!`; the migration and the routes
//! snippet are built dynamically (timestamp / formatting) by functions.

pub const USER_MODEL: &str = include_str!("auth/user_model.sl");
pub const APPLICATION_POLICY: &str = include_str!("auth/application_policy.sl");
pub const USER_POLICY: &str = include_str!("auth/user_policy.sl");
pub const AUTH_HELPER: &str = include_str!("auth/auth_helper.sl");
pub const CURRENT_USER_MIDDLEWARE: &str = include_str!("auth/current_user_middleware.sl");
pub const SESSIONS_CONTROLLER: &str = include_str!("auth/sessions_controller.sl");
pub const REGISTRATIONS_CONTROLLER: &str = include_str!("auth/registrations_controller.sl");
pub const PASSWORDS_CONTROLLER: &str = include_str!("auth/passwords_controller.sl");
pub const CONFIRMATIONS_CONTROLLER: &str = include_str!("auth/confirmations_controller.sl");
pub const AUTH_MAILER: &str = include_str!("auth/auth_mailer.sl");
pub const SESSIONS_NEW_VIEW: &str = include_str!("auth/sessions_new.html.slv");
pub const REGISTRATIONS_NEW_VIEW: &str = include_str!("auth/registrations_new.html.slv");
pub const PASSWORDS_NEW_VIEW: &str = include_str!("auth/passwords_new.html.slv");
pub const PASSWORDS_EDIT_VIEW: &str = include_str!("auth/passwords_edit.html.slv");
pub const CONFIRMATIONS_NEW_VIEW: &str = include_str!("auth/confirmations_new.html.slv");
pub const MAILER_RESET_PASSWORD_VIEW: &str = include_str!("auth/mailer_reset_password.html.slv");
pub const MAILER_CONFIRM_EMAIL_VIEW: &str = include_str!("auth/mailer_confirm_email.html.slv");
pub const POLICIES_CLAUDE: &str = include_str!("auth/policies_claude.md");

/// Migration creating the `users` collection with a unique index on `email`.
pub fn users_migration() -> String {
    r#"# Migration: create_users
# Generated by: soli generate auth

def up(db)
  db.create_collection("users")
  db.create_index("users", "idx_users_email", ["email"], { "unique": true })
end

def down(db)
  db.list_indexes("users").each do |idx|
    db.drop_index("users", idx["name"])
  end
  db.drop_collection("users")
end
"#
    .to_string()
}

/// Migration adding lookup indexes for the auth-flow token digests.
pub fn auth_token_indexes_migration() -> String {
    r#"# Migration: add_auth_token_indexes
# Generated by: soli generate auth

def up(db)
  db.create_index("users", "idx_users_reset_token", ["reset_token_digest"], {})
  db.create_index("users", "idx_users_confirmation_token", ["confirmation_token_digest"], {})
end

def down(db)
  db.drop_index("users", "idx_users_reset_token")
  db.drop_index("users", "idx_users_confirmation_token")
end
"#
    .to_string()
}

/// Routes appended to `config/routes.sl` for the auth flow.
pub const ROUTES_SNIPPET: &str = r#"

# Authentication routes (generated by `soli generate auth`)
get("/login", "sessions#new", name: "login")
post("/login", "sessions#create")
delete("/logout", "sessions#destroy", name: "logout")
get("/signup", "registrations#new", name: "signup")
post("/signup", "registrations#create")
"#;

/// Routes for the Devise-style flows (password reset, email confirmation).
/// Appended separately so existing apps that already ran `generate auth`
/// pick these up on a re-run.
pub const FLOWS_ROUTES_SNIPPET: &str = r#"

# Password reset + email confirmation (generated by `soli generate auth`)
get("/password/reset", "passwords#new", name: "password_reset")
post("/password/reset", "passwords#create")
get("/password/edit", "passwords#edit", name: "password_edit")
post("/password/update", "passwords#update")
get("/confirm_email", "confirmations#show", name: "confirm_email")
get("/confirmation/resend", "confirmations#new", name: "confirmation_resend")
post("/confirmation/resend", "confirmations#create")
"#;
