//! Template strings for `soli generate auth`.
//!
//! Static files are embedded with `include_str!`; the migration and the routes
//! snippet are built dynamically (timestamp / formatting) by functions.

pub const USER_MODEL: &str = include_str!("auth/user_model.sl");
pub const APPLICATION_POLICY: &str = include_str!("auth/application_policy.sl");
pub const USER_POLICY: &str = include_str!("auth/user_policy.sl");
pub const AUTH_HELPER: &str = include_str!("auth/auth_helper.sl");
pub const CURRENT_USER_MIDDLEWARE: &str = include_str!("auth/current_user_middleware.sl");
pub const SESSIONS_CONTROLLER: &str = include_str!("auth/sessions_controller.sl");
pub const REGISTRATIONS_CONTROLLER: &str = include_str!("auth/registrations_controller.sl");
pub const SESSIONS_NEW_VIEW: &str = include_str!("auth/sessions_new.html.slv");
pub const REGISTRATIONS_NEW_VIEW: &str = include_str!("auth/registrations_new.html.slv");
pub const POLICIES_CLAUDE: &str = include_str!("auth/policies_claude.md");

/// Migration creating the `users` collection with a unique index on `email`.
pub fn users_migration() -> String {
    r#"# Migration: create_users
# Generated by: soli generate auth

def up(db)
  db.create_collection("users")
  db.create_index("users", "idx_users_email", ["email"], { "unique": true })
end

def down(db)
  db.list_indexes("users").each do |idx|
    db.drop_index("users", idx["name"])
  end
  db.drop_collection("users")
end
"#
    .to_string()
}

/// Routes appended to `config/routes.sl` for the auth flow.
pub const ROUTES_SNIPPET: &str = r#"

# Authentication routes (generated by `soli generate auth`)
get("/login", "sessions#new", name: "login")
post("/login", "sessions#create")
delete("/logout", "sessions#destroy", name: "logout")
get("/signup", "registrations#new", name: "signup")
post("/signup", "registrations#create")
"#;
