//! Templates for `soli generate devices`.

pub const DEVICE_MODEL: &str = r#"# Device — push / native shell registration targets.
#
# Shells POST { platform, token } (or a web PushSubscription) after login.
# Pass Device.push_targets_for(user_id) into Push.deliver(..., { "targets": ... }).

class Device < Model
  validates("platform", { "presence": true })
  validates("token", { "presence": true })

  # Upsert by token so a reinstall or token rotate does not stack rows.
  static def register(user_id, platform, token, subscription = null) -> Any {
    let existing = Device.first_by("token", token)
    if existing {
      existing.user_id = user_id
      existing.platform = platform
      existing.subscription = subscription
      existing.save()
      return existing
    }
    Device.create({
      "user_id": user_id,
      "platform": platform,
      "token": token,
      "subscription": subscription
    })
  }

  static def push_targets_for(user_id) -> Array {
    Device.where("doc.user_id == @uid", { "uid": user_id }).all().map(fn(d) {
      if d.platform == "web" && d.subscription {
        { "platform": "web", "subscription": d.subscription }
      } else {
        { "platform": d.platform, "token": d.token }
      }
    })
  }

  static def prune_tokens(tokens) -> Int {
    let n = 0
    for token in tokens {
      let row = Device.first_by("token", token)
      if row {
        row.destroy()
        n = n + 1
      }
    }
    n
  }
end
"#;

pub const DEVICES_CONTROLLER: &str = r#"# DevicesController — register push tokens from native shells and browsers.
#
# POST /devices  { platform, token?, subscription? }
# DELETE /devices/:id

def create(req)
  let user_id = session_get("user_id")
  if user_id.nil?
    return { "status": 401, "body": json_stringify({ "error": "login required" }) }
  end

  let params = req["json"] || req["params"] || {}
  let platform = (params["platform"] || "").to_s().downcase()
  let token = params["token"]
  let subscription = params["subscription"]

  unless ["ios", "android", "web", "macos", "apple", "fcm"].includes?(platform)
    return { "status": 422, "body": json_stringify({ "error": "invalid platform" }) }
  end

  if platform == "web"
    if subscription.nil?
      return { "status": 422, "body": json_stringify({ "error": "subscription required for web" }) }
    end
    token = token || json_stringify(subscription)
  elsif token.nil? || token.to_s().blank?
    return { "status": 422, "body": json_stringify({ "error": "token required" }) }
  end

  let device = Device.register(user_id, platform, token.to_s(), subscription)
  {
    "status": 201,
    "headers": { "Content-Type": "application/json" },
    "body": json_stringify({
      "id": device._key || device.id,
      "platform": device.platform,
      "token": device.token
    })
  }
end

def destroy(req)
  let user_id = session_get("user_id")
  if user_id.nil?
    return { "status": 401, "body": json_stringify({ "error": "login required" }) }
  end

  let id = req["params"]["id"]
  let device = Device.find(id) rescue null
  if device.nil? || device.user_id != user_id
    return { "status": 404, "body": json_stringify({ "error": "not found" }) }
  end
  device.destroy()
  { "status": 204, "body": "" }
end
"#;

pub const DEVICES_HELPER: &str = r#"# Helpers for closed-app push with prune.

def deliver_to_user(user_id, payload, options = {})
  let targets = Device.push_targets_for(user_id)
  let opts = options.merge({ "targets": targets })
  let result = Push.deliver("user:#{str(user_id)}", payload, opts)
  Device.prune_tokens(result["prune"] || [])
  result
end
"#;

pub const ROUTES_MARKER: &str = "# --- soli generate devices ---";

pub fn routes_snippet() -> String {
    format!(
        r#"
{marker}
# Shell token POSTs (iOS/Android native code) often send a session cookie without
# Origin/Referer — the same-origin CSRF gate would reject them. Session auth is
# required in the controller; browser pages should still send X-CSRF-Token via
# soli.nativeBridge.registerDevice() when the meta tag is present.
skip_csrf("/devices/*");
post("/devices", "devices#create");
delete("/devices/:id", "devices#destroy");
# --- end soli generate devices ---
"#,
        marker = ROUTES_MARKER
    )
}

pub fn devices_migration() -> String {
    r#"# Migration: create_devices
# Generated by: soli generate devices
#
# begin/rescue so a re-run (or a collection SoliDB already auto-created on
# first model access) is not a hard failure.

def up(db)
  begin
    db.create_collection("devices")
  rescue
    print("  skip devices collection (already exists)")
  end

  begin
    db.create_index("devices", "idx_devices_token", ["token"], { "unique": true })
  rescue
    print("  skip idx_devices_token (already exists)")
  end

  begin
    db.create_index("devices", "idx_devices_user_id", ["user_id"], {})
  rescue
    print("  skip idx_devices_user_id (already exists)")
  end
end

def down(db)
  begin
    db.list_indexes("devices").each do |idx|
      db.drop_index("devices", idx["name"])
    end
  rescue
    print("  skip dropping devices indexes (collection is gone)")
  end

  begin
    db.drop_collection("devices")
  rescue
    print("  skip dropping devices collection (already gone)")
  end
end
"#
    .to_string()
}
