//! Migration template strings

/// Migration template
pub fn migration_template(
    migration_name: &str,
    name: &str,
    model_name: &str,
    collection: &str,
    indexes: &str,
) -> String {
    format!(
        r#"# Migration: {migration_name}
# Generated by: soli generate scaffold {name}

def up(db)
  # Create collection for {model_name}
  db.create_collection("{collection}")

  # Create indexes
{indexes}
end

def down(db)
  # Drop indexes
  db.list_indexes("{collection}").each do |idx|
    db.drop_index("{collection}", idx["name"])
  end

  # Drop collection
  db.drop_collection("{collection}")
end
"#,
        migration_name = migration_name,
        name = name,
        model_name = model_name,
        collection = collection,
        indexes = indexes
    )
}
