//! Migration template strings

/// Migration template
pub fn migration_template(
    migration_name: &str,
    name: &str,
    model_name: &str,
    collection: &str,
    indexes: &str,
) -> String {
    format!(
        r#"// Migration: {migration_name}
// Generated by: soli generate scaffold {name}

fn up(db: Any) -> Any {{
    // Create collection for {model_name}
    db.create_collection("{collection}");

    // Create indexes
{indexes}
}}

fn down(db: Any) -> Any {{
    // Drop indexes
    <% db.list_indexes("{collection}").each(fn(idx) {{
        db.drop_index("{collection}", idx["name"]);
    }}) %>

    // Drop collection
    db.drop_collection("{collection}");
}}
"#,
        migration_name = migration_name,
        name = name,
        model_name = model_name,
        collection = collection,
        indexes = indexes
    )
}
