//! Templates for `soli generate oauth <provider>`.

pub const OAUTH_IDENTITY_MODEL: &str = include_str!("oauth/oauth_identity_model.sl");
pub const OAUTH_CLIENT_SERVICE: &str = include_str!("oauth/oauth_client_service.sl");
pub const GITHUB_OAUTH_SERVICE: &str = include_str!("oauth/github_oauth_service.sl");
pub const GOOGLE_OAUTH_SERVICE: &str = include_str!("oauth/google_oauth_service.sl");
pub const OAUTH_CONTROLLER: &str = include_str!("oauth/oauth_controller.sl");

pub const ROUTES_MARKER: &str = "# --- soli generate oauth ---";

pub fn routes_snippet() -> String {
    format!(
        r#"
{ROUTES_MARKER}
get("/auth/:provider", "oauth#start")
get("/auth/:provider/callback", "oauth#callback")
"#
    )
}

pub fn identities_migration() -> String {
    r#"# Migration: create_oauth_identities
# Generated by: soli generate oauth

def up(db)
  db.create_collection("oauth_identities")
  db.create_index("oauth_identities", "idx_oauth_provider_uid", ["provider", "uid"], { "unique": true })
  db.create_index("oauth_identities", "idx_oauth_user_id", ["user_id"], {})
end

def down(db)
  db.list_indexes("oauth_identities").each do |idx|
    db.drop_index("oauth_identities", idx["name"])
  end
  db.drop_collection("oauth_identities")
end
"#
    .to_string()
}
