//! Templates for `soli generate offline` — outbox / sync endpoints.

pub const SYNC_CONTROLLER: &str = r#"# SyncController — offline outbox drain + pull.
# Generated by `soli generate offline`.
#
# The shell or page holds pending mutations client-side and POSTs them here
# when the radio returns. Pull returns documents changed since `since`.

def push(req)
  let user_id = session_get("user_id")
  if user_id.nil?
    return { "status": 401, "body": json_stringify({ "error": "login required" }) }
  end

  let body = req["json"] || {}
  let items = body["items"] || []
  let accepted = []
  let rejected = []

  for item in items {
    let client_id = item["id"]
    begin
      # App-specific: map item["method"] / item["path"] / item["body"] onto models.
      # Default: record the outbox row for an operator to inspect.
      SyncEvent.create({
        "user_id": user_id,
        "client_id": client_id,
        "method": item["method"],
        "path": item["path"],
        "payload": item["body"],
        "created_at": item["created_at"] || datetime_now()
      })
      accepted.push(client_id)
    rescue err
      rejected.push({ "id": client_id, "error": str(err) })
    end
  }

  {
    "status": 200,
    "headers": { "Content-Type": "application/json" },
    "body": json_stringify({ "accepted": accepted, "rejected": rejected })
  }
end

def pull(req)
  let user_id = session_get("user_id")
  if user_id.nil?
    return { "status": 401, "body": json_stringify({ "error": "login required" }) }
  end

  let since = (req["query"] || {})["since"]
  # App-specific: return documents the client should merge.
  let events = if since.present?
    SyncEvent.where("doc.user_id == @uid AND doc.created_at > @since", {
      "uid": user_id,
      "since": since
    }).order("created_at", "asc").limit(200).all()
  else
    SyncEvent.where("doc.user_id == @uid", { "uid": user_id })
      .order("created_at", "asc").limit(200).all()
  end

  {
    "status": 200,
    "headers": { "Content-Type": "application/json" },
    "body": json_stringify({
      "events": events,
      "server_time": datetime_now()
    })
  }
end
"#;

pub const SYNC_EVENT_MODEL: &str = r#"# SyncEvent — server-side log of offline outbox items (optional audit).

class SyncEvent < Model
end
"#;

pub const CLIENT_OUTBOX_JS: &str = r#"// Minimal offline outbox for a Soli shell / PWA page.
// Usage: soliOutbox.enqueue({ method: "POST", path: "/pings", body: {...} })
//        await soliOutbox.flush()
(function () {
  "use strict";
  var KEY = "soli_outbox_v1";

  function load() {
    try { return JSON.parse(localStorage.getItem(KEY) || "[]"); }
    catch (e) { return []; }
  }
  function save(items) {
    localStorage.setItem(KEY, JSON.stringify(items));
  }

  window.soliOutbox = {
    enqueue: function (item) {
      var items = load();
      items.push({
        id: item.id || (Date.now() + "-" + Math.random().toString(36).slice(2)),
        method: item.method || "POST",
        path: item.path,
        body: item.body || {},
        created_at: item.created_at || new Date().toISOString()
      });
      save(items);
      return items[items.length - 1].id;
    },
    pending: function () { return load(); },
    flush: function () {
      var items = load();
      if (!items.length) return Promise.resolve({ accepted: [], rejected: [] });
      return fetch("/sync/push", {
        method: "POST",
        credentials: "same-origin",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ items: items })
      }).then(function (r) { return r.json(); }).then(function (result) {
        var accepted = {};
        (result.accepted || []).forEach(function (id) { accepted[id] = true; });
        save(items.filter(function (it) { return !accepted[it.id]; }));
        return result;
      });
    }
  };

  window.addEventListener("online", function () {
    window.soliOutbox.flush().catch(function () {});
  });
})();
"#;

pub const ROUTES_MARKER: &str = "# --- soli generate offline ---";

pub fn routes_snippet() -> String {
    format!(
        r#"
{marker}
# Outbox flush from a shell may lack Origin; session is required in the controller.
skip_csrf("/sync/*");
post("/sync/push", "sync#push");
get("/sync/pull", "sync#pull");
# --- end soli generate offline ---
"#,
        marker = ROUTES_MARKER
    )
}

pub fn sync_events_migration() -> String {
    r#"# Migration: create_sync_events
# Generated by: soli generate offline

def up(db)
  begin
    db.create_collection("sync_events")
  rescue
    # already exists
  end

  begin
    db.create_index("sync_events", "idx_sync_events_user", ["user_id"], {})
  rescue
  end

  begin
    db.create_index("sync_events", "idx_sync_events_created", ["created_at"], {})
  rescue
  end
end

def down(db)
  begin
    db.drop_collection("sync_events")
  rescue
  end
end
"#
    .to_string()
}
