//! Template strings for `soli generate oidc_provider`.
//!
//! Static files are embedded with `include_str!`; the migrations and the
//! routes snippet are built by functions so they can carry a timestamp.

pub const OIDC_CONFIG: &str = include_str!("oidc/oidc_config_service.sl");
pub const OIDC_HELPER: &str = include_str!("oidc/oidc_helper_service.sl");
pub const OAUTH_CLIENT_MODEL: &str = include_str!("oidc/oauth_client_model.sl");
pub const OAUTH_AUTHORIZATION_CODE_MODEL: &str =
    include_str!("oidc/oauth_authorization_code_model.sl");
pub const OAUTH_REFRESH_TOKEN_MODEL: &str = include_str!("oidc/oauth_refresh_token_model.sl");
pub const OAUTH_CONSENT_MODEL: &str = include_str!("oidc/oauth_consent_model.sl");
pub const OAUTH_REVOCATION_MODEL: &str = include_str!("oidc/oauth_revocation_model.sl");
pub const OIDC_DISCOVERY_CONTROLLER: &str = include_str!("oidc/oidc_discovery_controller.sl");
pub const OAUTH_AUTHORIZATIONS_CONTROLLER: &str =
    include_str!("oidc/oauth_authorizations_controller.sl");
pub const OAUTH_TOKENS_CONTROLLER: &str = include_str!("oidc/oauth_tokens_controller.sl");
pub const OAUTH_USERINFO_CONTROLLER: &str = include_str!("oidc/oauth_userinfo_controller.sl");
pub const OAUTH_SESSIONS_CONTROLLER: &str = include_str!("oidc/oauth_sessions_controller.sl");
pub const AUTHORIZATIONS_NEW_VIEW: &str = include_str!("oidc/oauth_authorizations_new.html.slv");
pub const AUTHORIZATIONS_ERROR_VIEW: &str =
    include_str!("oidc/oauth_authorizations_error.html.slv");

/// Collections + the lookup and uniqueness indexes for them.
///
/// SoliDB creates a collection on first *model* access, so the collections
/// here are only needed because this migration runs before any model has been
/// touched and an index cannot be attached to a collection that does not
/// exist. Existing ones are skipped rather than re-created, since a plain
/// `create_collection` on an auto-created collection is a 409.
pub fn oauth_indexes_migration() -> String {
    // The unique index on code_digest is the database-level backstop for
    // single-use authorization codes: even if the application-level burn ever
    // raced, the second insert could not land.
    r#"# Migration: add_oauth_indexes
# Generated by: soli generate oidc_provider

const OAUTH_COLLECTIONS = ["oauth_clients", "oauth_authorization_codes",
                           "oauth_refresh_tokens", "oauth_consents", "oauth_revocations"]

def up(db)
  existing = db.list_collections().map(fn(c) c["name"])
  OAUTH_COLLECTIONS.each do |name|
    db.create_collection(name) unless existing.includes?(name)
  end

  db.create_index("oauth_clients", "idx_oauth_clients_client_id", ["client_id"], { "unique": true })
  db.create_index("oauth_authorization_codes", "idx_oauth_codes_digest", ["code_digest"],
                  { "unique": true })
  db.create_index("oauth_authorization_codes", "idx_oauth_codes_expires", ["expires_at"], {})
  db.create_index("oauth_refresh_tokens", "idx_oauth_refresh_digest", ["token_digest"],
                  { "unique": true })
  db.create_index("oauth_refresh_tokens", "idx_oauth_refresh_chain", ["chain_id"], {})
  db.create_index("oauth_consents", "idx_oauth_consents_user_client", ["user_key", "client_id"],
                  { "unique": true })
  db.create_index("oauth_revocations", "idx_oauth_revocations_jti", ["jti"], { "unique": true })
end

def down(db)
  db.drop_index("oauth_clients", "idx_oauth_clients_client_id")
  db.drop_index("oauth_authorization_codes", "idx_oauth_codes_digest")
  db.drop_index("oauth_authorization_codes", "idx_oauth_codes_expires")
  db.drop_index("oauth_refresh_tokens", "idx_oauth_refresh_digest")
  db.drop_index("oauth_refresh_tokens", "idx_oauth_refresh_chain")
  db.drop_index("oauth_consents", "idx_oauth_consents_user_client")
  db.drop_index("oauth_revocations", "idx_oauth_revocations_jti")

  # The collections themselves are left in place: dropping them would discard
  # live grants, and re-running `up` recreates only what is missing.
end
"#
    .to_string()
}

/// Routes appended to `config/routes.sl`.
pub const ROUTES_SNIPPET: &str = r#"

# OpenID Connect provider (generated by `soli generate oidc_provider`)
#
# /oauth/token and /oauth/revoke are called server-to-server by relying
# parties, which have no browser Origin — the same-origin CSRF gate would
# reject every legitimate call. They authenticate the *client* instead
# (client_secret_basic / client_secret_post) and, for public clients, PKCE.
# The consent POST below is a real browser form and keeps CSRF protection.
skip_csrf("/oauth/token")
skip_csrf("/oauth/revoke")

get("/.well-known/openid-configuration", "oidc_discovery#openid_configuration", name: "oidc_discovery")
get("/.well-known/jwks.json", "oidc_discovery#jwks", name: "oidc_jwks")
get("/oauth/authorize", "oauth_authorizations#new", name: "oauth_authorize")
post("/oauth/authorize", "oauth_authorizations#create")
post("/oauth/token", "oauth_tokens#create", name: "oauth_token")
get("/oauth/userinfo", "oauth_userinfo#show", name: "oauth_userinfo")
post("/oauth/userinfo", "oauth_userinfo#show")
post("/oauth/revoke", "oauth_tokens#revoke", name: "oauth_revoke")
get("/oauth/logout", "oauth_sessions#end_session", name: "oauth_end_session")
"#;
