//! Lock file (soli.lock) for pinning resolved package versions.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use super::package::Dependency;

/// A resolved lock file entry.
#[derive(Debug, Clone)]
pub struct LockEntry {
    /// Package name
    pub name: String,
    /// Git repository URL
    pub url: String,
    /// Full resolved commit SHA
    pub resolved_rev: String,
    /// Path to cached package on disk
    pub cache_path: PathBuf,
    /// Original tag or branch requested (for display)
    pub ref_spec: Option<String>,
}

/// Content hash recorded for a package at one resolved revision.
///
/// The hash is bound to the revision it was computed for: once a package is
/// re-resolved to a different commit/version the old hash no longer applies
/// and a new one is recorded on first install (trust on first use).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IntegrityRecord {
    /// The `resolved_rev` the hash was computed for.
    pub resolved_rev: String,
    /// `sha256-<hex>` digest of the extracted tree (see `tree_hash`).
    pub hash: String,
}

/// The lock file containing all resolved package entries.
#[derive(Debug, Clone, Default)]
pub struct LockFile {
    /// Resolved packages keyed by name
    pub packages: HashMap<String, LockEntry>,
    /// Extracted-tree content hashes keyed by package name.
    ///
    /// Kept beside `packages` rather than inside `LockEntry` so the entry
    /// type (constructed by callers with struct literals) stays unchanged.
    pub integrity: HashMap<String, IntegrityRecord>,
}

const LOCK_HEADER: &str = "# This file is auto-generated by soli. Do not edit manually.\n\
                            # It pins exact versions of dependencies for reproducible builds.\n";

/// Prefix of an integrity line: `#@integrity <name>|<resolved_rev>|sha256-<hex>`.
///
/// Written as a `#` line on purpose. Every soli release before this one
/// parses the lock file by skipping any trimmed line that starts with `#`
/// and `splitn(5, '|')`-ing the rest, where the 5th field is the free-form
/// `ref_spec`. Appending the hash as a 6th `|` field would have landed inside
/// `ref_spec` for those parsers (turning `v1.0.0` into `v1.0.0|sha256-…`,
/// which breaks `is_satisfied`); a line without `|` would have been rejected
/// as "Invalid lock file line". A comment line is the only shape they ignore.
const INTEGRITY_PREFIX: &str = "#@integrity ";

impl LockFile {
    /// Load a lock file from disk.
    pub fn load(path: &Path) -> Result<Self, String> {
        if !path.exists() {
            return Ok(LockFile::default());
        }

        let content =
            fs::read_to_string(path).map_err(|e| format!("Failed to read lock file: {}", e))?;
        Self::parse(&content)
    }

    /// Parse lock file content.
    fn parse(content: &str) -> Result<Self, String> {
        let mut packages = HashMap::new();
        let mut integrity = HashMap::new();

        for line in content.lines() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix(INTEGRITY_PREFIX) {
                let parts: Vec<&str> = rest.trim().splitn(3, '|').collect();
                if parts.len() < 3 || parts[0].is_empty() || parts[1].is_empty() {
                    return Err(format!("Invalid lock file integrity line: {}", line));
                }
                // Only sha256 is understood. A digest in some other scheme
                // (written by a later soli) is ignored rather than failing,
                // so the lock file stays readable; it is replaced on save.
                if parts[2].starts_with(super::tree_hash::HASH_PREFIX) {
                    integrity.insert(
                        parts[0].to_string(),
                        IntegrityRecord {
                            resolved_rev: parts[1].to_string(),
                            hash: parts[2].to_string(),
                        },
                    );
                }
                continue;
            }
            // Skip comments and empty lines
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let parts: Vec<&str> = line.splitn(5, '|').collect();
            if parts.len() < 4 {
                return Err(format!("Invalid lock file line: {}", line));
            }

            let name = parts[0].to_string();
            let url = parts[1].to_string();
            let resolved_rev = parts[2].to_string();
            let cache_path = PathBuf::from(parts[3]);
            let ref_spec = if parts.len() >= 5 && !parts[4].is_empty() {
                Some(parts[4].to_string())
            } else {
                None
            };

            packages.insert(
                name.clone(),
                LockEntry {
                    name,
                    url,
                    resolved_rev,
                    cache_path,
                    ref_spec,
                },
            );
        }

        Ok(LockFile {
            packages,
            integrity,
        })
    }

    /// The recorded content hash for `name`, if one was recorded for exactly
    /// `resolved_rev`.
    pub fn integrity_for(&self, name: &str, resolved_rev: &str) -> Option<&str> {
        self.integrity
            .get(name)
            .filter(|record| record.resolved_rev == resolved_rev)
            .map(|record| record.hash.as_str())
    }

    /// Record the content hash of `name` at `resolved_rev`, replacing any
    /// hash recorded for an earlier revision.
    pub fn set_integrity(&mut self, name: &str, resolved_rev: &str, hash: &str) {
        self.integrity.insert(
            name.to_string(),
            IntegrityRecord {
                resolved_rev: resolved_rev.to_string(),
                hash: hash.to_string(),
            },
        );
    }

    /// Save the lock file to disk.
    pub fn save(&self, path: &Path) -> Result<(), String> {
        fs::write(path, self.render()).map_err(|e| format!("Failed to write lock file: {}", e))
    }

    /// Serialize the lock file.
    fn render(&self) -> String {
        let mut content = String::from(LOCK_HEADER);
        content.push('\n');

        // Sort entries for deterministic output
        let mut entries: Vec<_> = self.packages.values().collect();
        entries.sort_by(|a, b| a.name.cmp(&b.name));

        for entry in entries {
            content.push_str(&format!(
                "{}|{}|{}|{}|{}\n",
                entry.name,
                entry.url,
                entry.resolved_rev,
                entry.cache_path.display(),
                entry.ref_spec.as_deref().unwrap_or("")
            ));
            // Only a hash recorded for the entry's current revision is kept;
            // one left over from a previous revision is stale.
            if let Some(hash) = self.integrity_for(&entry.name, &entry.resolved_rev) {
                content.push_str(&format!(
                    "{}{}|{}|{}\n",
                    INTEGRITY_PREFIX, entry.name, entry.resolved_rev, hash
                ));
            }
        }

        content
    }

    /// Check if a lock entry satisfies the given dependency.
    pub fn is_satisfied(&self, name: &str, dep: &Dependency) -> bool {
        let entry = match self.packages.get(name) {
            Some(e) => e,
            None => return false,
        };

        // Check that the cache directory exists
        if !entry.cache_path.exists() {
            return false;
        }

        match dep {
            Dependency::Git {
                url,
                tag,
                branch,
                rev,
                ..
            } => {
                // URL must match
                if entry.url != *url {
                    return false;
                }
                // If a specific rev is requested, it must match
                if let Some(r) = rev {
                    return entry.resolved_rev.starts_with(r);
                }
                // For tag/branch, the ref_spec should match what was requested
                if let Some(t) = tag {
                    return entry.ref_spec.as_deref() == Some(t.as_str());
                }
                if let Some(b) = branch {
                    return entry.ref_spec.as_deref() == Some(b.as_str());
                }
                // No specific ref requested, any resolved rev is fine
                true
            }
            Dependency::Version(ver) => entry.resolved_rev == *ver,
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lock_file_roundtrip() {
        let mut lock = LockFile::default();
        lock.packages.insert(
            "math".to_string(),
            LockEntry {
                name: "math".to_string(),
                url: "https://github.com/user/soli-math".to_string(),
                resolved_rev: "abc123def456".to_string(),
                cache_path: PathBuf::from("/home/user/.soli/packages/math-abc123def456"),
                ref_spec: Some("v1.0.0".to_string()),
            },
        );

        let content = {
            let mut out = String::from(LOCK_HEADER);
            out.push('\n');
            for entry in lock.packages.values() {
                out.push_str(&format!(
                    "{}|{}|{}|{}|{}\n",
                    entry.name,
                    entry.url,
                    entry.resolved_rev,
                    entry.cache_path.display(),
                    entry.ref_spec.as_deref().unwrap_or("")
                ));
            }
            out
        };

        let parsed = LockFile::parse(&content).unwrap();
        assert_eq!(parsed.packages.len(), 1);

        let entry = &parsed.packages["math"];
        assert_eq!(entry.url, "https://github.com/user/soli-math");
        assert_eq!(entry.resolved_rev, "abc123def456");
        assert_eq!(entry.ref_spec.as_deref(), Some("v1.0.0"));
    }

    fn sample_entry(name: &str, rev: &str, ref_spec: Option<&str>) -> LockEntry {
        LockEntry {
            name: name.to_string(),
            url: format!("https://github.com/user/{}", name),
            resolved_rev: rev.to_string(),
            cache_path: PathBuf::from(format!("/home/user/.soli/packages/{}-{}", name, rev)),
            ref_spec: ref_spec.map(|s| s.to_string()),
        }
    }

    const SAMPLE_HASH: &str =
        "sha256-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

    #[test]
    fn integrity_round_trips() {
        let mut lock = LockFile::default();
        lock.packages.insert(
            "math".to_string(),
            sample_entry("math", "abc123", Some("v1.0.0")),
        );
        lock.packages
            .insert("util".to_string(), sample_entry("util", "def456", None));
        lock.set_integrity("math", "abc123", SAMPLE_HASH);

        let rendered = lock.render();
        assert!(rendered.contains(&format!("#@integrity math|abc123|{}\n", SAMPLE_HASH)));

        let parsed = LockFile::parse(&rendered).unwrap();
        assert_eq!(parsed.packages.len(), 2);
        assert_eq!(parsed.integrity_for("math", "abc123"), Some(SAMPLE_HASH));
        assert_eq!(parsed.integrity_for("util", "def456"), None);
        assert_eq!(
            parsed.packages["math"].ref_spec.as_deref(),
            Some("v1.0.0"),
            "the integrity line must not leak into ref_spec"
        );
        // Re-rendering is stable.
        assert_eq!(parsed.render(), rendered);
    }

    #[test]
    fn round_trip_without_integrity_writes_no_integrity_line() {
        let mut lock = LockFile::default();
        lock.packages.insert(
            "math".to_string(),
            sample_entry("math", "abc123", Some("v1.0.0")),
        );
        let rendered = lock.render();
        assert!(!rendered.contains(INTEGRITY_PREFIX));
        let parsed = LockFile::parse(&rendered).unwrap();
        assert!(parsed.integrity.is_empty());
        assert_eq!(parsed.integrity_for("math", "abc123"), None);
    }

    #[test]
    fn integrity_is_bound_to_the_revision() {
        let mut lock = LockFile::default();
        lock.packages
            .insert("math".to_string(), sample_entry("math", "newrev", None));
        lock.set_integrity("math", "oldrev", SAMPLE_HASH);
        assert_eq!(lock.integrity_for("math", "newrev"), None);
        // A stale hash is not written back.
        assert!(!lock.render().contains(INTEGRITY_PREFIX));
    }

    #[test]
    fn old_format_lock_file_parses() {
        // Exactly what soli wrote before integrity lines existed.
        let content = "# This file is auto-generated by soli. Do not edit manually.\n\
                       # It pins exact versions of dependencies for reproducible builds.\n\
                       \n\
                       math|https://github.com/user/soli-math|abc123|/tmp/math-abc123|v1.0.0\n\
                       util|https://github.com/user/soli-util|def456|/tmp/util-def456|\n";
        let parsed = LockFile::parse(content).unwrap();
        assert_eq!(parsed.packages.len(), 2);
        assert_eq!(parsed.packages["math"].ref_spec.as_deref(), Some("v1.0.0"));
        assert_eq!(parsed.packages["util"].ref_spec, None);
        assert!(parsed.integrity.is_empty());
    }

    /// The parser every earlier soli release shipped, verbatim in behaviour:
    /// skip trimmed `#`/empty lines, `splitn(5, '|')` the rest.
    fn legacy_parse(content: &str) -> Result<Vec<(String, Option<String>)>, String> {
        let mut out = Vec::new();
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = line.splitn(5, '|').collect();
            if parts.len() < 4 {
                return Err(format!("Invalid lock file line: {}", line));
            }
            let ref_spec = if parts.len() >= 5 && !parts[4].is_empty() {
                Some(parts[4].to_string())
            } else {
                None
            };
            out.push((parts[0].to_string(), ref_spec));
        }
        Ok(out)
    }

    #[test]
    fn new_format_is_tolerated_by_the_legacy_parser() {
        let mut lock = LockFile::default();
        lock.packages.insert(
            "math".to_string(),
            sample_entry("math", "abc123", Some("v1.0.0")),
        );
        lock.set_integrity("math", "abc123", SAMPLE_HASH);
        let legacy = legacy_parse(&lock.render()).expect("legacy parser must accept it");
        assert_eq!(legacy, [("math".to_string(), Some("v1.0.0".to_string()))]);
    }

    #[test]
    fn malformed_integrity_line_is_an_error() {
        let content = "math|u|abc|/tmp|v1\n#@integrity math|abc\n";
        assert!(LockFile::parse(content).is_err());
    }

    #[test]
    fn unknown_digest_scheme_is_ignored() {
        let content = "math|u|abc|/tmp|v1\n#@integrity math|abc|blake9-ffff\n";
        let parsed = LockFile::parse(content).unwrap();
        assert_eq!(parsed.integrity_for("math", "abc"), None);
    }

    #[test]
    fn test_is_satisfied_matching() {
        let mut lock = LockFile::default();
        // `is_satisfied` requires the cache path to exist; use a real temp dir
        // rather than a hardcoded `/tmp`, which is absent on Windows.
        let cache_dir = tempfile::tempdir().unwrap();
        let cache_path = cache_dir.path().to_path_buf();
        lock.packages.insert(
            "math".to_string(),
            LockEntry {
                name: "math".to_string(),
                url: "https://github.com/user/soli-math".to_string(),
                resolved_rev: "abc123def456".to_string(),
                cache_path: cache_path.clone(),
                ref_spec: Some("v1.0.0".to_string()),
            },
        );

        let dep = Dependency::Git {
            url: "https://github.com/user/soli-math".to_string(),
            tag: Some("v1.0.0".to_string()),
            branch: None,
            rev: None,
        };

        assert!(lock.is_satisfied("math", &dep));
    }

    #[test]
    fn test_is_satisfied_wrong_url() {
        let mut lock = LockFile::default();
        lock.packages.insert(
            "math".to_string(),
            LockEntry {
                name: "math".to_string(),
                url: "https://github.com/user/soli-math".to_string(),
                resolved_rev: "abc123".to_string(),
                cache_path: PathBuf::from("/tmp"),
                ref_spec: Some("v1.0.0".to_string()),
            },
        );

        let dep = Dependency::Git {
            url: "https://github.com/other/soli-math".to_string(),
            tag: Some("v1.0.0".to_string()),
            branch: None,
            rev: None,
        };

        assert!(!lock.is_satisfied("math", &dep));
    }
}
