# Discord OAuth 2.0 (authorization code).
# Generated by: soli generate oauth discord
#
# Env: DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET, DISCORD_REDIRECT_URI
#
# Discord has no OIDC userinfo endpoint: the profile comes from /users/@me, and
# its `verified` flag is what makes the email safe to link on.

class DiscordOauth
  static def authorize_url(state, code_challenge = nil)
    query = [
      "client_id=#{url_encode(getenv("DISCORD_CLIENT_ID").to_s)}",
      "redirect_uri=#{url_encode(getenv("DISCORD_REDIRECT_URI").to_s)}",
      "response_type=code",
      "scope=#{url_encode("identify email")}",
      "state=#{url_encode(state)}",
      "prompt=none"
    ]

    "https://discord.com/oauth2/authorize?#{query.join("&")}"
  end

  static def exchange_code(code)
    body = [
      "code=#{url_encode(code)}",
      "client_id=#{url_encode(getenv("DISCORD_CLIENT_ID").to_s)}",
      "client_secret=#{url_encode(getenv("DISCORD_CLIENT_SECRET").to_s)}",
      "redirect_uri=#{url_encode(getenv("DISCORD_REDIRECT_URI").to_s)}",
      "grant_type=authorization_code"
    ].join("&")
    response = HTTP.request(
      "POST",
      "https://discord.com/api/oauth2/token",
      {"Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json"},
      body
    )

    DiscordOauth._json_body(response, "token exchange")
  end

  static def fetch_user(access_token)
    response = HTTP.request(
      "GET",
      "https://discord.com/api/users/@me",
      {"Authorization": "Bearer #{access_token}", "Accept": "application/json"}
    )

    DiscordOauth._json_body(response, "profile fetch")
  end

  static def _json_body(response, step)
    status = response["status"]
    body = response["body"].to_s
    throw "Discord #{step} failed (HTTP #{status}): #{body}" unless status >= 200 && status < 300

    json_parse(body)
  end

  static def complete!(code)
    token_data = DiscordOauth.exchange_code(code)
    if token_data["error"]
      throw "Discord token exchange failed: #{token_data["error_description"] || token_data["error"]}"
    end

    profile = DiscordOauth.fetch_user(token_data["access_token"])
    throw "Discord: email is not verified" unless profile["verified"] == true

    name = profile["global_name"] || profile["username"]
    user = OauthClient.find_or_create_user("discord", profile["id"], profile["email"], name, profile)
    OauthClient.sign_in(user)
    user
  end
end
