# GitHub OAuth 2.0 (authorization code).
# Generated by: soli generate oauth github
#
# Env: GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, GITHUB_REDIRECT_URI

class GithubOauth
  static def authorize_url(state) -> String {
    let client_id = getenv("GITHUB_CLIENT_ID")
    let redirect = getenv("GITHUB_REDIRECT_URI")
    "https://github.com/login/oauth/authorize?" +
      "client_id=" + client_id +
      "&redirect_uri=" + redirect +
      "&scope=read:user%20user:email" +
      "&state=" + state
  }

  # `HTTP.request` is the only form that sends headers: `HTTP.post`/`HTTP.get`
  # inspect their options hash for `timeout` alone, so a `"headers"` key there
  # is silently dropped — and they return the body as a String, not a response
  # hash. Headers are the 3rd positional argument; the body is the 4th.
  static def exchange_code(code) -> Any {
    let response = HTTP.request(
      "POST",
      "https://github.com/login/oauth/access_token",
      {
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      json_stringify({
        "client_id": getenv("GITHUB_CLIENT_ID"),
        "client_secret": getenv("GITHUB_CLIENT_SECRET"),
        "code": code,
        "redirect_uri": getenv("GITHUB_REDIRECT_URI")
      })
    )
    GithubOauth._json_body(response, "token exchange")
  }

  static def fetch_user(access_token) -> Any {
    let response = HTTP.request(
      "GET",
      "https://api.github.com/user",
      {
        "Authorization": "Bearer " + access_token,
        "Accept": "application/json",
        "User-Agent": "soli-oauth"
      }
    )
    GithubOauth._json_body(response, "profile fetch")
  }

  static def fetch_emails(access_token) -> Any {
    let response = HTTP.request(
      "GET",
      "https://api.github.com/user/emails",
      {
        "Authorization": "Bearer " + access_token,
        "Accept": "application/json",
        "User-Agent": "soli-oauth"
      }
    )
    GithubOauth._json_body(response, "email fetch")
  }

  # `HTTP.request` returns the response instead of raising on a non-2xx, so the
  # status has to be read. Without this a 401 surfaced as a JSON parse error on
  # GitHub's error page.
  static def _json_body(response, step) -> Any {
    let status = response["status"]
    let body = response["body"].to_s
    unless status >= 200 && status < 300
      throw "GitHub " + step + " failed (HTTP " + str(status) + "): " + body
    end

    json_parse(body)
  }

  static def primary_email(emails) -> Any {
    return null unless emails
    for e in emails {
      if e["primary"] && e["verified"]
        return e["email"]
      end
    }
    for e in emails {
      return e["email"] if e["verified"]
    }
    null
  }

  # Full callback: exchange code → profile → User → session.
  static def complete!(code) -> Any {
    let token_data = GithubOauth.exchange_code(code)
    if token_data["error"]
      throw "GitHub token exchange failed: " + str(token_data["error_description"] || token_data["error"])
    end
    let access_token = token_data["access_token"]
    let profile = GithubOauth.fetch_user(access_token)
    let email = profile["email"]
    if email.blank?
      email = GithubOauth.primary_email(GithubOauth.fetch_emails(access_token))
    end
    let user = OauthClient.find_or_create_user(
      "github",
      profile["id"],
      email,
      profile["name"] || profile["login"],
      profile
    )
    OauthClient.sign_in(user)
    user
  }
end
