# GitHub OAuth 2.0 (authorization code).
# Generated by: soli generate oauth github
#
# Env: GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, GITHUB_REDIRECT_URI

class GithubOauth
  static def authorize_url(state) -> String {
    let client_id = getenv("GITHUB_CLIENT_ID")
    let redirect = getenv("GITHUB_REDIRECT_URI")
    "https://github.com/login/oauth/authorize?" +
      "client_id=" + client_id +
      "&redirect_uri=" + redirect +
      "&scope=read:user%20user:email" +
      "&state=" + state
  }

  static def exchange_code(code) -> Any {
    let response = HTTP.post(
      "https://github.com/login/oauth/access_token",
      json_stringify({
        "client_id": getenv("GITHUB_CLIENT_ID"),
        "client_secret": getenv("GITHUB_CLIENT_SECRET"),
        "code": code,
        "redirect_uri": getenv("GITHUB_REDIRECT_URI")
      }),
      {
        "headers": {
          "Content-Type": "application/json",
          "Accept": "application/json"
        }
      }
    )
    json_parse(response["body"] || response.body)
  }

  static def fetch_user(access_token) -> Any {
    let response = HTTP.get(
      "https://api.github.com/user",
      {
        "headers": {
          "Authorization": "Bearer " + access_token,
          "Accept": "application/json",
          "User-Agent": "soli-oauth"
        }
      }
    )
    json_parse(response["body"] || response.body)
  }

  static def fetch_emails(access_token) -> Any {
    let response = HTTP.get(
      "https://api.github.com/user/emails",
      {
        "headers": {
          "Authorization": "Bearer " + access_token,
          "Accept": "application/json",
          "User-Agent": "soli-oauth"
        }
      }
    )
    json_parse(response["body"] || response.body)
  }

  static def primary_email(emails) -> Any {
    return null unless emails
    for e in emails {
      if e["primary"] && e["verified"]
        return e["email"]
      end
    }
    for e in emails {
      return e["email"] if e["verified"]
    }
    null
  }

  # Full callback: exchange code → profile → User → session.
  static def complete!(code) -> Any {
    let token_data = GithubOauth.exchange_code(code)
    if token_data["error"]
      throw "GitHub token exchange failed: " + str(token_data["error_description"] || token_data["error"])
    end
    let access_token = token_data["access_token"]
    let profile = GithubOauth.fetch_user(access_token)
    let email = profile["email"]
    if email.blank?
      email = GithubOauth.primary_email(GithubOauth.fetch_emails(access_token))
    end
    let user = OauthClient.find_or_create_user(
      "github",
      profile["id"],
      email,
      profile["name"] || profile["login"],
      profile
    )
    OauthClient.sign_in(user)
    user
  }
end
