# GitLab OAuth 2.0 / OIDC (authorization code + PKCE S256).
# Generated by: soli generate oauth gitlab
#
# Env: GITLAB_CLIENT_ID, GITLAB_CLIENT_SECRET, GITLAB_REDIRECT_URI
# Optional: GITLAB_BASE_URL for a self-hosted instance (default https://gitlab.com)

class GitlabOauth
  static def base_url
    url = (getenv("GITLAB_BASE_URL") ?? "https://gitlab.com").to_s.trim
    while url.ends_with?("/")
      url = url.substring(0, url.length - 1)
    end

    url
  end

  static def authorize_url(state, code_challenge = nil)
    query = [
      "client_id=#{url_encode(getenv("GITLAB_CLIENT_ID").to_s)}",
      "redirect_uri=#{url_encode(getenv("GITLAB_REDIRECT_URI").to_s)}",
      "response_type=code",
      "scope=#{url_encode("openid email profile")}",
      "state=#{url_encode(state)}",
      "code_challenge=#{url_encode(code_challenge.to_s)}",
      "code_challenge_method=S256"
    ]

    "#{GitlabOauth.base_url}/oauth/authorize?#{query.join("&")}"
  end

  # `HTTP.request` is the only form that sends headers, and it returns the
  # response instead of raising on a non-2xx, so the status is read below.
  static def exchange_code(code)
    body = [
      "code=#{url_encode(code)}",
      "client_id=#{url_encode(getenv("GITLAB_CLIENT_ID").to_s)}",
      "client_secret=#{url_encode(getenv("GITLAB_CLIENT_SECRET").to_s)}",
      "redirect_uri=#{url_encode(getenv("GITLAB_REDIRECT_URI").to_s)}",
      "grant_type=authorization_code",
      "code_verifier=#{url_encode(OauthClient.pkce_verifier.to_s)}"
    ].join("&")
    response = HTTP.request(
      "POST",
      "#{GitlabOauth.base_url}/oauth/token",
      {"Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json"},
      body
    )

    GitlabOauth._json_body(response, "token exchange")
  end

  static def fetch_userinfo(access_token)
    response = HTTP.request(
      "GET",
      "#{GitlabOauth.base_url}/oauth/userinfo",
      {"Authorization": "Bearer #{access_token}", "Accept": "application/json"}
    )

    GitlabOauth._json_body(response, "userinfo fetch")
  end

  static def _json_body(response, step)
    status = response["status"]
    body = response["body"].to_s
    throw "GitLab #{step} failed (HTTP #{status}): #{body}" unless status >= 200 && status < 300

    json_parse(body)
  end

  static def complete!(code)
    token_data = GitlabOauth.exchange_code(code)
    if token_data["error"]
      throw "GitLab token exchange failed: #{token_data["error_description"] || token_data["error"]}"
    end

    profile = GitlabOauth.fetch_userinfo(token_data["access_token"])
    throw "GitLab: email is not verified" unless profile["email_verified"] == true

    user = OauthClient.find_or_create_user("gitlab", profile["sub"], profile["email"], profile["name"], profile)
    OauthClient.sign_in(user)
    user
  end
end
