# Google OAuth 2.0 / OIDC (authorization code + PKCE plain verifier).
# Generated by: soli generate oauth google
#
# Env: GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI

class GoogleOauth
  static def authorize_url(state, code_challenge) -> String {
    let client_id = getenv("GOOGLE_CLIENT_ID")
    let redirect = getenv("GOOGLE_REDIRECT_URI")
    "https://accounts.google.com/o/oauth2/v2/auth?" +
      "client_id=" + client_id +
      "&redirect_uri=" + redirect +
      "&response_type=code" +
      "&scope=openid%20email%20profile" +
      "&state=" + state +
      "&code_challenge=" + code_challenge +
      "&code_challenge_method=plain" +
      "&access_type=online" +
      "&prompt=select_account"
  }

  static def exchange_code(code) -> Any {
    let verifier = OauthClient.pkce_verifier()
    let body = "code=" + code +
      "&client_id=" + getenv("GOOGLE_CLIENT_ID") +
      "&client_secret=" + getenv("GOOGLE_CLIENT_SECRET") +
      "&redirect_uri=" + getenv("GOOGLE_REDIRECT_URI") +
      "&grant_type=authorization_code"
    body = body + "&code_verifier=" + verifier if verifier
    let response = HTTP.post(
      "https://oauth2.googleapis.com/token",
      body,
      {
        "headers": {
          "Content-Type": "application/x-www-form-urlencoded"
        }
      }
    )
    json_parse(response["body"] || response.body)
  }

  static def fetch_userinfo(access_token) -> Any {
    let response = HTTP.get(
      "https://openidconnect.googleapis.com/v1/userinfo",
      {
        "headers": {
          "Authorization": "Bearer " + access_token
        }
      }
    )
    json_parse(response["body"] || response.body)
  }

  static def complete!(code) -> Any {
    let token_data = GoogleOauth.exchange_code(code)
    if token_data["error"]
      throw "Google token exchange failed: " + str(token_data["error_description"] || token_data["error"])
    end
    let access_token = token_data["access_token"]
    let profile = GoogleOauth.fetch_userinfo(access_token)
    unless profile["email_verified"] == true || profile["email_verified"] == "true"
      throw "Google: email is not verified"
    end
    let user = OauthClient.find_or_create_user(
      "google",
      profile["sub"],
      profile["email"],
      profile["name"],
      profile
    )
    OauthClient.sign_in(user)
    user
  }
end
