# LinkedIn "Sign In with LinkedIn using OpenID Connect" (authorization code).
# Generated by: soli generate oauth linkedin
#
# Env: LINKEDIN_CLIENT_ID, LINKEDIN_CLIENT_SECRET, LINKEDIN_REDIRECT_URI

class LinkedinOauth
  static def authorize_url(state, code_challenge = nil)
    query = [
      "response_type=code",
      "client_id=#{url_encode(getenv("LINKEDIN_CLIENT_ID").to_s)}",
      "redirect_uri=#{url_encode(getenv("LINKEDIN_REDIRECT_URI").to_s)}",
      "scope=#{url_encode("openid profile email")}",
      "state=#{url_encode(state)}"
    ]

    "https://www.linkedin.com/oauth/v2/authorization?#{query.join("&")}"
  end

  static def exchange_code(code)
    body = [
      "grant_type=authorization_code",
      "code=#{url_encode(code)}",
      "client_id=#{url_encode(getenv("LINKEDIN_CLIENT_ID").to_s)}",
      "client_secret=#{url_encode(getenv("LINKEDIN_CLIENT_SECRET").to_s)}",
      "redirect_uri=#{url_encode(getenv("LINKEDIN_REDIRECT_URI").to_s)}"
    ].join("&")
    response = HTTP.request(
      "POST",
      "https://www.linkedin.com/oauth/v2/accessToken",
      {"Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json"},
      body
    )

    LinkedinOauth._json_body(response, "token exchange")
  end

  static def fetch_userinfo(access_token)
    response = HTTP.request(
      "GET",
      "https://api.linkedin.com/v2/userinfo",
      {"Authorization": "Bearer #{access_token}", "Accept": "application/json"}
    )

    LinkedinOauth._json_body(response, "userinfo fetch")
  end

  static def _json_body(response, step)
    status = response["status"]
    body = response["body"].to_s
    throw "LinkedIn #{step} failed (HTTP #{status}): #{body}" unless status >= 200 && status < 300

    json_parse(body)
  end

  static def complete!(code)
    token_data = LinkedinOauth.exchange_code(code)
    if token_data["error"]
      throw "LinkedIn token exchange failed: #{token_data["error_description"] || token_data["error"]}"
    end

    profile = LinkedinOauth.fetch_userinfo(token_data["access_token"])
    throw "LinkedIn: email is not verified" unless profile["email_verified"] == true

    user = OauthClient.find_or_create_user("linkedin", profile["sub"], profile["email"], profile["name"], profile)
    OauthClient.sign_in(user)
    user
  end
end
