# Microsoft identity platform (Entra ID), authorization code + PKCE S256.
# Generated by: soli generate oauth microsoft
#
# Env: MICROSOFT_CLIENT_ID, MICROSOFT_CLIENT_SECRET, MICROSOFT_REDIRECT_URI,
#      MICROSOFT_TENANT  (your tenant id or domain — required)
#
# Microsoft does not verify the `email` claim, and in a multi-tenant app a
# foreign tenant can present someone else's address (the "nOAuth" class of
# account takeover). So this service refuses the multi-tenant endpoints
# (`common`, `organizations`, `consumers`): sign-in is limited to the one tenant
# whose directory you control, and that is what makes its email safe to link on.

class MicrosoftOauth
  static def tenant
    tenant = getenv("MICROSOFT_TENANT").to_s.trim
    throw "MICROSOFT_TENANT is required (a tenant id or domain)" if tenant.blank?
    if ["common", "organizations", "consumers"].includes?(tenant.downcase)
      throw "MICROSOFT_TENANT must name your own tenant, not a multi-tenant endpoint"
    end

    tenant
  end

  static def authorize_url(state, code_challenge = nil)
    query = [
      "client_id=#{url_encode(getenv("MICROSOFT_CLIENT_ID").to_s)}",
      "redirect_uri=#{url_encode(getenv("MICROSOFT_REDIRECT_URI").to_s)}",
      "response_type=code",
      "response_mode=query",
      "scope=#{url_encode("openid email profile")}",
      "state=#{url_encode(state)}",
      "code_challenge=#{url_encode(code_challenge.to_s)}",
      "code_challenge_method=S256",
      "prompt=select_account"
    ]

    "https://login.microsoftonline.com/#{url_encode(MicrosoftOauth.tenant)}/oauth2/v2.0/authorize?#{query.join("&")}"
  end

  static def exchange_code(code)
    body = [
      "code=#{url_encode(code)}",
      "client_id=#{url_encode(getenv("MICROSOFT_CLIENT_ID").to_s)}",
      "client_secret=#{url_encode(getenv("MICROSOFT_CLIENT_SECRET").to_s)}",
      "redirect_uri=#{url_encode(getenv("MICROSOFT_REDIRECT_URI").to_s)}",
      "grant_type=authorization_code",
      "code_verifier=#{url_encode(OauthClient.pkce_verifier.to_s)}"
    ].join("&")
    response = HTTP.request(
      "POST",
      "https://login.microsoftonline.com/#{url_encode(MicrosoftOauth.tenant)}/oauth2/v2.0/token",
      {"Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json"},
      body
    )

    MicrosoftOauth._json_body(response, "token exchange")
  end

  static def fetch_userinfo(access_token)
    response = HTTP.request(
      "GET",
      "https://graph.microsoft.com/oidc/userinfo",
      {"Authorization": "Bearer #{access_token}", "Accept": "application/json"}
    )

    MicrosoftOauth._json_body(response, "userinfo fetch")
  end

  static def _json_body(response, step)
    status = response["status"]
    body = response["body"].to_s
    throw "Microsoft #{step} failed (HTTP #{status}): #{body}" unless status >= 200 && status < 300

    json_parse(body)
  end

  static def complete!(code)
    token_data = MicrosoftOauth.exchange_code(code)
    if token_data["error"]
      throw "Microsoft token exchange failed: #{token_data["error_description"] || token_data["error"]}"
    end

    profile = MicrosoftOauth.fetch_userinfo(token_data["access_token"])
    user = OauthClient.find_or_create_user("microsoft", profile["sub"], profile["email"], profile["name"], profile)
    OauthClient.sign_in(user)
    user
  end
end
