# OAuth client callbacks — generated by soli generate oauth.
#
# GET /auth/:provider          → start
# GET /auth/:provider/callback → callback

def start(req)
  let provider = (req["params"]["provider"] || "").to_s().downcase()
  unless ["github", "google"].includes?(provider)
    return { "status": 404, "body": "Unknown OAuth provider" }
  end

  let state = OauthClient.begin_state(provider)
  let url = null

  if provider == "github"
    url = GithubOauth.authorize_url(state)
  elsif provider == "google"
    let challenge = OauthClient.begin_pkce()
    url = GoogleOauth.authorize_url(state, challenge)
  end

  redirect(url)
end

def callback(req)
  let provider = (req["params"]["provider"] || "").to_s().downcase()
  let params = req["query"] || req["query_params"] || {}

  unless OauthClient.valid_state?(params["state"])
    OauthClient.clear_state()
    return { "status": 403, "body": "Invalid OAuth state — try signing in again" }
  end

  if params["error"].present?
    OauthClient.clear_state()
    return {
      "status": 401,
      "body": "Authorization denied: " + str(params["error_description"] || params["error"])
    }
  end

  let code = params["code"]
  if code.blank?
    OauthClient.clear_state()
    return { "status": 400, "body": "Missing authorization code" }
  end

  try {
    if provider == "github"
      GithubOauth.complete!(code)
    elsif provider == "google"
      GoogleOauth.complete!(code)
    else
      return { "status": 404, "body": "Unknown OAuth provider" }
    end
  } catch error {
    OauthClient.clear_state()
    return { "status": 401, "body": "OAuth failed: " + str(error) }
  }

  redirect("/" rescue "/")
end
