# OauthIdentity — links a User to an external OAuth provider account.
# Generated by: soli generate oauth

class OauthIdentity < Model
  validates("provider", { "presence": true })
  validates("uid", { "presence": true })
  validates("user_id", { "presence": true })

  belongs_to("user")

  # Find an identity by provider + uid (e.g. "github", "12345").
  static def find_for(provider, uid) -> Any {
    OauthIdentity.where({ "provider": provider, "uid": uid.to_s() }).first
  }

  # Attach or create identity for a user after a successful OAuth callback.
  static def link!(user_id, provider, uid, email = null, raw = null) -> Any {
    let existing = OauthIdentity.find_for(provider, uid)
    if existing {
      existing.email = email if email
      existing.raw = raw if raw
      existing.save()
      return existing
    }
    OauthIdentity.create({
      "user_id": user_id,
      "provider": provider,
      "uid": uid.to_s(),
      "email": email,
      "raw": raw
    })
  }
end
