# OAuth client callbacks — generated by soli generate oauth.
#
# GET /auth/:provider          → start
# GET /auth/:provider/callback → callback
#
# A provider is the `<Name>Oauth` service class that `soli generate oauth <name>`
# wrote (`GithubOauth`, `GoogleOauth`, `GitlabOauth`, …), found by name, so adding
# a provider never means editing this file. Each service exposes
# `authorize_url(state, code_challenge)` and `complete!(code)`.

# The class for a provider name, or nil. The name is checked against a strict
# pattern first: it comes straight from the URL.
def oauth_service_for(provider)
  return nil if provider.match("^[a-z][a-z0-9]{1,19}$").nil?

  const_get("#{provider.capitalize}Oauth") rescue nil
end

# GET /auth/:provider — redirects to the provider with a fresh state and PKCE challenge.
def start(req)
  provider = (req["params"]["provider"] || "").to_s().downcase()
  service = oauth_service_for(provider)
  return { "status": 404, "body": "Unknown OAuth provider" } if service.nil?

  state = OauthClient.begin_state(provider)
  challenge = OauthClient.begin_pkce()

  redirect_external(service.authorize_url(state, challenge))
end

# GET /auth/:provider/callback — checks state, exchanges the code, signs the user in.
def callback(req)
  provider = (req["params"]["provider"] || "").to_s().downcase()
  params = req["query"] || req["query_params"] || {}

  unless OauthClient.valid_state?(params["state"])
    OauthClient.clear_state()
    return { "status": 403, "body": "Invalid OAuth state — try signing in again" }
  end

  # The provider must be the one this browser session started with, or a
  # callback for one provider could complete a flow begun for another.
  service = oauth_service_for(provider)
  if service.nil? || session_get("oauth_provider") != provider
    OauthClient.clear_state()
    return { "status": 404, "body": "Unknown OAuth provider" }
  end

  if params["error"].present?
    OauthClient.clear_state()
    return {
      "status": 401,
      "body": "Authorization denied: " + str(params["error_description"] || params["error"])
    }
  end

  code = params["code"]
  if code.blank?
    OauthClient.clear_state()
    return { "status": 400, "body": "Missing authorization code" }
  end

  try {
    service.complete!(code)
  } catch error {
    OauthClient.clear_state()
    return { "status": 401, "body": "OAuth failed: " + str(error) }
  }

  redirect("/" rescue "/")
end
