# Shared OAuth client helpers (state CSRF + optional PKCE).
# Generated by: soli generate oauth

class OauthClient
  # Store a random state token in the session and return it for the authorize URL.
  static def begin_state(provider) -> String {
    let state = Crypto.random_hex(32)
    session_set("oauth_state", state)
    session_set("oauth_provider", provider)
    state
  }

  # True when the callback `state` matches the one we issued.
  static def valid_state?(state) -> Bool {
    let expected = session_get("oauth_state")
    expected.present? && state.present? && expected.to_s() == state.to_s()
  }

  static def clear_state {
    session_delete("oauth_state")
    session_delete("oauth_provider")
    session_delete("oauth_pkce_verifier")
  }

  # PKCE (S256): store the verifier, return the code_challenge for the
  # authorize URL.
  #
  # `code_challenge = base64url(SHA256(verifier))`, unpadded, per RFC 7636 §4.2.
  # `Crypto.sha256` returns hex, so it is decoded back to bytes before
  # encoding — `Base64.urlsafe_encode` is already unpadded, which is what the
  # spec requires.
  #
  # This used to send the raw verifier with `code_challenge_method=plain`, which
  # is PKCE in name only: the challenge and the verifier were the same string,
  # so an attacker who intercepted the authorization request could complete the
  # exchange. Never ship `plain`.
  static def begin_pkce() -> String {
    let verifier = Crypto.random_hex(32)
    session_set("oauth_pkce_verifier", verifier)
    Base64.urlsafe_encode(Hex.decode(Crypto.sha256(verifier)))
  }

  static def pkce_verifier() -> Any {
    session_get("oauth_pkce_verifier")
  }

  # Find-or-create a User from a verified email, then link OauthIdentity.
  # Prefers verified emails only — never invent an account from a blank email.
  static def find_or_create_user(provider, uid, email, name = null, raw = null) -> Any {
    if email.blank?
      throw "OAuth: provider did not return a verified email"
    end

    let identity = OauthIdentity.find_for(provider, uid)
    if identity {
      let user = User.find(identity.user_id)
      return user
    }

    let user = User.find_by("email", email.downcase())
    if user.nil?
      # Password is random — this account signs in via OAuth only.
      let password = Crypto.random_hex(32)
      let result = User.create({
        "email": email.downcase(),
        "name": name || email.split("@")[0],
        "password": password,
        "password_confirmation": password,
        "email_confirmed_at": datetime_now()
      })
      if result["valid"] == false
        throw "OAuth: could not create user: " + str(result["errors"])
      end
      user = User.find(result["id"] || result["_key"])
    end

    OauthIdentity.link!(user["_key"] || user.id, provider, uid, email, raw)
    user
  }

  static def sign_in(user) {
    session_regenerate()
    session_set("user_id", user["_key"] || user.id)
    OauthClient.clear_state()
  }
end
